package phase05.d17_capstone;

import java.sql.SQLException;
import org.flywaydb.core.api.MigrationVersion;
import org.flywaydb.core.api.migration.Context;
import org.flywaydb.core.api.migration.JavaMigration;
import org.springframework.stereotype.Component;

/** B1: Java-owned Flyway migration. No hidden resource DDL. */
@Component
public final class CapstoneSchema implements JavaMigration {
    // Provided Flyway adapter; learner owns sql().
    @Override public MigrationVersion getVersion() { return MigrationVersion.fromVersion("1"); }
    @Override public String getDescription() { return "capstone schema"; }
    @Override public Integer getChecksum() { return sql().hashCode(); }
    @Override public boolean canExecuteInTransaction() { return true; }
    @Override public void migrate(Context context) throws SQLException {
        try (var statement = context.getConnection().createStatement()) {
            statement.execute(sql());
        }
    }

    public static String sql() {
        // SOLUTION-BEGIN throw B1
        return """
                CREATE TABLE customers (
                    id BIGINT PRIMARY KEY,
                    subject TEXT NOT NULL UNIQUE
                );
                CREATE TABLE products (
                    id BIGINT PRIMARY KEY,
                    name TEXT NOT NULL,
                    price NUMERIC(19,2) NOT NULL CHECK (price > 0),
                    stock INTEGER NOT NULL CHECK (stock >= 0)
                );
                CREATE TABLE orders (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    customer_id BIGINT NOT NULL REFERENCES customers(id),
                    status TEXT NOT NULL CHECK (status IN ('NEW','CANCELLED')),
                    currency CHAR(3) NOT NULL CHECK (currency = 'USD'),
                    created_at TIMESTAMPTZ NOT NULL
                );
                CREATE TABLE order_items (
                    order_id BIGINT NOT NULL REFERENCES orders(id),
                    product_id BIGINT NOT NULL REFERENCES products(id),
                    quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 1000),
                    unit_price NUMERIC(19,2) NOT NULL CHECK (unit_price > 0),
                    PRIMARY KEY (order_id, product_id)
                );
                """;
        // SOLUTION-END
    }
}
