package phase04.d04_indexes;

import java.sql.SQLException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;
import static org.junit.jupiter.api.Assertions.*;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_HistoryIndexTest {
    // Provided bootstrap: no learner index DDL, independent of B1 migrations.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE,
              price NUMERIC(19,2) NOT NULL CHECK(price >= 0), stock INTEGER NOT NULL CHECK(stock >= 0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              customer_id BIGINT NOT NULL REFERENCES customers(id), status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),
              created_at TIMESTAMP WITH TIME ZONE NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id),
              quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000), unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price >= 0),
              UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) SELECT n,'Customer ' || n FROM generate_series(1,100) n;
            INSERT INTO orders(id,customer_id,status,created_at)
            SELECT n,1 + n % 100,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00' + n * INTERVAL '1 second'
            FROM generate_series(1,20000) n;
            ANALYZE orders;
            """;
    private static PostgresFixture fixture;
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("B4 — catalog, plan và insert trước/sau index trên cùng dữ liệu")
    void b04_catalogAndBoundedWriteObservation() throws SQLException {
        String ddl = Ex01_HistoryIndex.indexDdl(); // TODO must fail before any rejection assertion.
        String beforePlan = plan();
        long beforeStart = System.nanoTime();
        int beforeInserted = insertBatch();
        long beforeNanos = System.nanoTime() - beforeStart;
        assertEquals(500, beforeInserted);
        assertEquals(20500, countOrders());
        execute("DELETE FROM orders WHERE id > 20000");
        assertEquals(20000, countOrders());
        execute(ddl);
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("""
                     SELECT indexdef FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'orders'
                     AND indexdef LIKE '%(customer_id, created_at, id)%'
                     """)) {
            assertTrue(r.next(), "Catalog phải có index customer/time/id đúng thứ tự");
            System.out.println("B4 catalog: " + r.getString(1));
        }
        String afterPlan = plan();
        long afterStart = System.nanoTime();
        int afterInserted = insertBatch();
        long afterNanos = System.nanoTime() - afterStart;
        assertEquals(500, afterInserted);
        assertEquals(20500, countOrders());
        assertFalse(beforePlan.isBlank());
        assertFalse(afterPlan.isBlank());
        System.out.printf("B4 dataset=20000 orders/100 customers; each INSERT=500; before=%d ns, after=%d ns%n",
                beforeNanos, afterNanos);
        System.out.println("B4 before:\n" + beforePlan + "B4 after:\n" + afterPlan);
        // Observation only: no timing threshold, node golden or benchmark conclusion.
    }

    @Test @DisplayName("Q5 — quan sát dữ liệu/plan workload có sẵn, rồi viết OBSERVATION Q5")
    void q05_experimentRuns() throws SQLException {
        assertEquals(20000, countOrders());
        String observed = plan();
        assertTrue(observed.contains("actual") && observed.contains("Buffers"));
        System.out.println("Q5 provided workload, 20000 orders/100 customers:\n" + observed);
        // No index answer here; compare with B4 and fill OBSERVATION Q5 manually.
    }

    private int insertBatch() throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            return s.executeUpdate("""
                    INSERT INTO orders(id,customer_id,status,created_at)
                    SELECT n,1 + n % 100,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00' + n * INTERVAL '1 second'
                    FROM generate_series(20001,20500) n
                    """);
        }
    }
    private long countOrders() throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT COUNT(*) FROM orders")) { r.next(); return r.getLong(1); }
    }
    private void execute(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute(sql); }
    }
    private String plan() throws SQLException {
        // Provided read workload; learner target here is index DDL, not this SELECT.
        try (var c = fixture.dataSource().getConnection(); var s = c.prepareStatement("""
                EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT)
                SELECT id,created_at,status FROM orders WHERE customer_id = ? ORDER BY created_at,id
                """)) {
            s.setLong(1, 1L);
            try (var r = s.executeQuery()) {
                var text = new StringBuilder();
                while (r.next()) text.append(r.getString(1)).append('\n');
                return text.toString();
            }
        }
    }
}
