package phase04.d12_relationships;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.persistence.EntityManagerFactory;
import jakarta.persistence.PersistenceException;
import java.sql.SQLException;
import java.time.Instant;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_OrderMappingTest {
    private static PostgresFixture fixture;
    private EntityManagerFactory emf;
    // Provided four-table Task 1 schema; not relationship helper answers. Currency: USD.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai');
            INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4),(2,'Book',5.00,4);
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException {
        fixture.reset(SCHEMA, SEED);
        var config = new Configuration()
                .addAnnotatedClass(Ex01_OrderMapping.Customer.class).addAnnotatedClass(Ex01_OrderMapping.Product.class)
                .addAnnotatedClass(Ex01_OrderMapping.Order.class).addAnnotatedClass(Ex01_OrderMapping.OrderItem.class)
                .setProperty("hibernate.hbm2ddl.auto", "validate").setProperty("hibernate.jdbc.time_zone", "UTC");
        config.getProperties().put("hibernate.connection.datasource", fixture.dataSource());
        emf = config.buildSessionFactory();
    }
    @AfterEach void closeMapping() { if (emf != null) emf.close(); }

    @Test @DisplayName("B12 — Thêm item cập nhật hai phía, cascade PERSIST và FK thực sau flush")
    void b12_addMaintainsOwningForeignKey() throws SQLException {
        long orderId;
        long itemId;
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = new Ex01_OrderMapping.Order(em.find(Ex01_OrderMapping.Customer.class, 1L), Instant.parse("2026-01-01T00:00:00Z"));
            var item = new Ex01_OrderMapping.OrderItem(em.find(Ex01_OrderMapping.Product.class, 1L), 2);
            order.addItem(item);
            order.addItem(item); // same object is idempotent, not duplicate insert
            assertEquals(1, order.items().size());
            assertSame(order, item.order);
            assertThrows(UnsupportedOperationException.class, () -> order.items().clear());
            em.persist(order); // item persists through selected cascade only
            em.flush();
            orderId = order.id;
            itemId = item.id;
            assertEquals(orderId, ((Number) em.createNativeQuery("SELECT order_id FROM order_items WHERE id=:id")
                    .setParameter("id", itemId).getSingleResult()).longValue());
            assertEquals(0, count("order_items")); // independent connection cannot see uncommitted child
            em.getTransaction().commit();
        }
        try (var c = fixture.dataSource().getConnection(); var s = c.prepareStatement("SELECT order_id,quantity,unit_price FROM order_items WHERE id=?")) {
            s.setLong(1, itemId);
            try (var rows = s.executeQuery()) {
                assertTrue(rows.next());
                assertEquals(orderId, rows.getLong(1));
                assertEquals(2, rows.getInt(2));
                assertEquals(new java.math.BigDecimal("12.50"), rows.getBigDecimal(3));
                assertFalse(rows.next());
            }
        }
        assertEquals(2, count("products"));
        System.out.println("B12: committed child FK matches order; quantity=2, unit_price=12.50 USD");
    }

    @Test @DisplayName("B12 — Product lazy proxy vẫn cung cấp giá server cho item")
    void b12_lazyProductReferenceUsesServerPrice() throws SQLException {
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = new Ex01_OrderMapping.Order(em.getReference(Ex01_OrderMapping.Customer.class, 1L), Instant.parse("2026-01-01T00:00:00Z"));
            order.addItem(new Ex01_OrderMapping.OrderItem(em.getReference(Ex01_OrderMapping.Product.class, 1L), 1));
            assertEquals(new java.math.BigDecimal("12.50"), order.items().getFirst().unitPrice);
            em.persist(order);
            em.getTransaction().commit();
        }
        assertEquals(1, count("order_items"));
    }

    @Test @DisplayName("Q4 — Item thuộc lifecycle order: removeItem gây orphan DELETE, product còn nguyên")
    void q04_removeDeletesOnlyOwnedChild() throws SQLException {
        long orderId = createOrder();
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = em.find(Ex01_OrderMapping.Order.class, orderId);
            var item = order.items().getFirst();
            order.removeItem(item);
            assertNull(item.order);
            assertTrue(order.items().isEmpty());
            em.flush();
            assertEquals(0L, ((Number) em.createNativeQuery("SELECT count(*) FROM order_items").getSingleResult()).longValue());
            em.getTransaction().commit();
        }
        assertEquals(0, count("order_items"));
        assertEquals(1, count("orders"));
        assertEquals(2, count("products"));
    }

    @Test @DisplayName("B12 — Parent proxy thêm lại child có sẵn không đổi FK; vẫn từ chối parent khác")
    void b12_parentProxyAddIsIdempotentAndRejectsReparenting() throws SQLException {
        long orderId = createOrder();
        long otherId = createOrder();
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = em.getReference(Ex01_OrderMapping.Order.class, orderId);
            var item = order.items().getFirst();
            assertSame(order, item.order); // association holds proxy, helper runs on target
            order.addItem(item); // positive control: same owner must not be rejected
            assertEquals(1, order.items().size());
            var other = em.getReference(Ex01_OrderMapping.Order.class, otherId);
            assertThrows(IllegalArgumentException.class, () -> other.addItem(item));
            assertThrows(IllegalArgumentException.class, () -> other.removeItem(item));
            assertThrows(IllegalArgumentException.class, () -> order.addItem(
                    new Ex01_OrderMapping.OrderItem(em.getReference(Ex01_OrderMapping.Product.class, 1L), 2)));
            assertSame(order, item.order);
            em.flush();
            em.getTransaction().commit();
        }
        try (var c = fixture.dataSource().getConnection();
             var s = c.prepareStatement("SELECT count(*) FROM order_items WHERE order_id=? AND product_id=1")) {
            s.setLong(1, orderId);
            try (var rows = s.executeQuery()) { rows.next(); assertEquals(1, rows.getLong(1)); }
        }
        assertEquals(2, count("orders"));
        assertEquals(2, count("order_items"));
        assertEquals(2, count("products"));
        assertEquals(1, count("customers"));
    }

    @Test @DisplayName("B12 — Parent proxy xóa child owned thật, orphan DELETE giữ parent/product")
    void b12_parentProxyRemoveDeletesOwnedChild() throws SQLException {
        long orderId = createOrder();
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = em.getReference(Ex01_OrderMapping.Order.class, orderId);
            var item = order.items().getFirst();
            assertSame(order, item.order);
            order.removeItem(item);
            assertNull(item.order);
            assertTrue(order.items().isEmpty());
            em.flush();
            em.getTransaction().commit();
        }
        assertEquals(0, count("order_items"));
        assertEquals(1, count("orders"));
        assertEquals(2, count("products"));
        assertEquals(1, count("customers"));
    }

    @Test @DisplayName("B12 — Xóa parent qua ORM xóa child owned, không cascade REMOVE sang product/customer")
    void b12_parentRemovalPreservesSharedEntities() throws SQLException {
        long orderId = createOrder();
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            em.remove(em.find(Ex01_OrderMapping.Order.class, orderId));
            em.flush();
            em.getTransaction().commit();
        }
        assertEquals(0, count("orders"));
        assertEquals(0, count("order_items"));
        assertEquals(2, count("products"));
        assertEquals(1, count("customers"));
    }

    @Test @DisplayName("B12 — DELETE parent bằng SQL dùng ON DELETE CASCADE của DB, không callbacks ORM")
    void b12_databaseCascadeIsSeparateFromOrm() throws SQLException {
        long orderId = createOrder();
        try (var c = fixture.dataSource().getConnection(); var s = c.prepareStatement("DELETE FROM orders WHERE id=?")) {
            s.setLong(1, orderId);
            assertEquals(1, s.executeUpdate());
        }
        assertEquals(0, count("order_items"));
        assertEquals(2, count("products"));
        assertEquals(1, count("customers"));
    }

    @Test @DisplayName("Q2 — Chỉ đổi inverse list không điền owning FK; DB từ chối NULL")
    void q02_inverseOnly_experimentRuns() {
        // Deliberately broken provided fixture, not alternate learner implementation.
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = new Ex01_OrderMapping.Order(em.find(Ex01_OrderMapping.Customer.class, 1L), Instant.parse("2026-01-01T00:00:00Z"));
            var item = new Ex01_OrderMapping.OrderItem(em.find(Ex01_OrderMapping.Product.class, 1L), 1);
            order.items.add(item);
            assertNull(item.order);
            assertThrows(PersistenceException.class, () -> { em.persist(order); em.flush(); });
            em.getTransaction().rollback();
        }
    }

    @Test @DisplayName("B12 — Reject item NULL, quantity ngoài miền, product trùng và reparent ngầm")
    void b12_validatesHelpersAfterPositiveControl() {
        try (var em = emf.createEntityManager()) {
            var customer = em.find(Ex01_OrderMapping.Customer.class, 1L);
            var product = em.find(Ex01_OrderMapping.Product.class, 1L);
            var order = new Ex01_OrderMapping.Order(customer, Instant.now());
            var item = new Ex01_OrderMapping.OrderItem(product, 1);
            order.addItem(item); // TODO cannot masquerade as expected rejection.
            assertThrows(IllegalArgumentException.class, () -> order.addItem(null));
            assertThrows(IllegalArgumentException.class, () -> order.addItem(new Ex01_OrderMapping.OrderItem(product, 0)));
            assertThrows(IllegalArgumentException.class, () -> order.addItem(new Ex01_OrderMapping.OrderItem(product, 1001)));
            assertThrows(IllegalArgumentException.class, () -> order.addItem(new Ex01_OrderMapping.OrderItem(null, 1)));
            assertThrows(IllegalArgumentException.class, () -> order.addItem(new Ex01_OrderMapping.OrderItem(product, 2)));
            var other = new Ex01_OrderMapping.Order(customer, Instant.now());
            assertThrows(IllegalArgumentException.class, () -> other.addItem(item));
            assertThrows(IllegalArgumentException.class, () -> other.removeItem(item));
            assertSame(order, item.order);
            order.removeItem(item);
            assertNull(item.order);
            assertThrows(IllegalArgumentException.class, () -> order.removeItem(null));
            assertThrows(IllegalArgumentException.class, () -> order.removeItem(item));
        }
    }

    private long createOrder() {
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var order = new Ex01_OrderMapping.Order(em.find(Ex01_OrderMapping.Customer.class, 1L), Instant.parse("2026-01-01T00:00:00Z"));
            order.addItem(new Ex01_OrderMapping.OrderItem(em.find(Ex01_OrderMapping.Product.class, 1L), 1));
            em.persist(order);
            em.getTransaction().commit();
            return order.id;
        }
    }
    private static long count(String table) throws SQLException {
        // Only test-owned literal identifiers, never user input.
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var rows = s.executeQuery("SELECT count(*) FROM " + table)) {
            rows.next();
            return rows.getLong(1);
        }
    }
}
