package phase04.d13_fetching;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.persistence.EntityManagerFactory;
import java.math.BigDecimal;
import java.sql.SQLException;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicInteger;
import org.hibernate.cfg.Configuration;
import org.hibernate.resource.jdbc.spi.StatementInspector;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_OrderHistoryProjectionTest {
    private static PostgresFixture fixture;
    private EntityManagerFactory emf;
    private final AtomicInteger selects = new AtomicInteger();
    private final List<String> sql = new ArrayList<>();
    // Provided fixed Task 1 schema, not learner read queries. Currency: USD.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException {
        seed(3);
        emf = bootstrap();
    }
    private EntityManagerFactory bootstrap() {
        var config = new Configuration()
                .addAnnotatedClass(Ex01_OrderHistoryProjection.Customer.class).addAnnotatedClass(Ex01_OrderHistoryProjection.Product.class)
                .addAnnotatedClass(Ex01_OrderHistoryProjection.Order.class).addAnnotatedClass(Ex01_OrderHistoryProjection.OrderItem.class)
                .setProperty("hibernate.hbm2ddl.auto", "validate").setProperty("hibernate.jdbc.time_zone", "UTC");
        config.getProperties().put("hibernate.connection.datasource", fixture.dataSource());
        config.getProperties().put("hibernate.session_factory.statement_inspector", (StatementInspector) statement -> {
            if (statement.stripLeading().toLowerCase(java.util.Locale.ROOT).startsWith("select")) {
                selects.incrementAndGet();
                sql.add(statement);
            }
            return statement;
        });
        return config.buildSessionFactory();
    }
    @AfterEach void closeMapping() { if (emf != null) emf.close(); }

    @Test @DisplayName("Q1 / B13 — Trang đầy đủ DTO, SQL không tăng N+1 từ 3 lên 12 orders")
    void q01_b13_boundedQueriesAndCompleteRows() throws SQLException {
        var small = readPage(1, 0, 12); // same size covers all 3, then all 12 orders
        assertEquals(expected(1, 2, 3), small);
        int threeQueries = selects.get();
        assertTrue(threeQueries >= 1 && threeQueries <= 3, "Count real SELECTs, not empty fake result");
        List<String> smallSql = List.copyOf(sql);
        // No EntityManager/cache survives calls; reset fixed schema only between transactions.
        emf.close();
        resetWithTwelve();
        var large = readPage(1, 0, 12);
        assertEquals(expected(1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12), large);
        assertEquals(small, large.subList(0, 3));
        int twelveQueries = selects.get();
        assertTrue(twelveQueries >= 1 && twelveQueries <= 3);
        assertTrue(twelveQueries <= threeQueries + 1);
        System.out.println("B13 orders=3 page=12 selects=" + threeQueries + "; orders=12 page=12 selects=" + twelveQueries);
        smallSql.forEach(statement -> System.out.println("B13 SQL(3): " + statement));
        sql.forEach(statement -> System.out.println("B13 SQL(12): " + statement));
    }

    @Test @DisplayName("B13 — Predicate owner, tie-break, page 0-based, empty page và snapshot price")
    void b13_stableOwnerPagesAndImmutableDtos() throws SQLException {
        emf.close();
        resetWithTwelve();
        assertEquals(expected(1, 2), readPage(1, 0, 2));
        var second = readPage(1, 1, 2);
        assertEquals(expected(3, 4), second);
        assertEquals(expected(12), readPage(1, 11, 1));
        assertTrue(readPage(1, 12, 1).isEmpty());
        assertTrue(readPage(999, 0, 2).isEmpty());
        var foreign = readPage(2, 0, 2);
        assertEquals(1, foreign.size());
        assertEquals(900, foreign.getFirst().orderId());
        assertEquals("An", foreign.getFirst().customerName());
        assertEquals(2, foreign.getFirst().items().size());
        assertThrows(UnsupportedOperationException.class, () -> second.clear());
        assertThrows(UnsupportedOperationException.class, () -> second.getFirst().items().clear());
        assertEquals(new BigDecimal("10.00"), second.getFirst().items().getFirst().unitPrice());
    }

    @Test @DisplayName("B13 — Size 1..100, page nonnegative, owner ID và EntityManager hợp lệ")
    void b13_inputBoundsAfterPositiveControl() {
        try (var em = emf.createEntityManager()) {
            assertEquals(expected(1), Ex01_OrderHistoryProjection.page(em, 1, 0, 1));
            assertEquals(3, Ex01_OrderHistoryProjection.page(em, 1, 0, 100).size());
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(em, 1, -1, 1));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(em, 1, 0, 0));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(em, 1, 0, 101));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(em, 0, 0, 1));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(em, 1, Integer.MAX_VALUE, 100));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderHistoryProjection.page(null, 1, 0, 1));
        }
    }

    private List<Ex01_OrderHistoryProjection.OrderSummary> readPage(long customer, int page, int size) {
        selects.set(0); // AFTER seed/bootstrap, never counting repository mocks.
        sql.clear();
        try (var em = emf.createEntityManager()) {
            return Ex01_OrderHistoryProjection.page(em, customer, page, size);
        }
    }
    private static List<Ex01_OrderHistoryProjection.OrderSummary> expected(long... ids) {
        var expected = new ArrayList<Ex01_OrderHistoryProjection.OrderSummary>();
        for (long id : ids) {
            expected.add(new Ex01_OrderHistoryProjection.OrderSummary(id, Instant.parse("2026-01-01T00:00:00Z"), "Mai",
                    List.of(new Ex01_OrderHistoryProjection.ItemSummary("Tea", 2, new BigDecimal("10.00")),
                            new Ex01_OrderHistoryProjection.ItemSummary("Book", 1, new BigDecimal("5.00")))));
        }
        return List.copyOf(expected);
    }
    private void resetWithTwelve() throws SQLException {
        seed(12);
        emf = bootstrap();
    }
    private static void seed(int orders) throws SQLException {
        fixture.reset(SCHEMA, """
                INSERT INTO customers(id,name) VALUES (1,'Mai'),(2,'An');
                INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',99.00,50),(2,'Book',8.00,50);
                """);
        try (var c = fixture.dataSource().getConnection();
             var order = c.prepareStatement("INSERT INTO orders(id,customer_id,status,created_at) VALUES (?,?,'NEW','2026-01-01T00:00:00Z')");
             var items = c.prepareStatement("INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES (?,1,2,10.00),(?,2,1,5.00)")) {
            for (int i = 1; i <= orders + 1; i++) {
                long id = i <= orders ? i : 900;
                order.setLong(1, id); order.setLong(2, i <= orders ? 1 : 2); order.executeUpdate();
                items.setLong(1, id); items.setLong(2, id); items.executeUpdate();
            }
        }
    }
}
