package phase04.d07_transactions;

import static org.junit.jupiter.api.Assertions.*;

import java.math.BigDecimal;
import java.sql.SQLException;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_OrderTransactionTest {
    private static PostgresFixture fixture;
    // Provided independent schema, not learner d01 migrations or transaction answers.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai');
            INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4),(2,'Book',5.00,0),(3,'Bulk',0.01,1000);
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q1 — Order, items, stock và giá snapshot cùng commit")
    void q01_commitsOrderItemsAndServerPrice() throws SQLException {
        createControl();
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT customer_id,status,created_at FROM orders WHERE id=900")) {
            assertTrue(r.next());
            assertEquals(1, r.getLong(1));
            assertEquals("NEW", r.getString(2));
            assertNotNull(r.getTimestamp(3).toInstant());
        }
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT quantity,unit_price FROM order_items WHERE order_id=900")) {
            assertTrue(r.next());
            assertEquals(1, r.getInt(1));
            assertEquals(new BigDecimal("12.50"), r.getBigDecimal(2));
            assertFalse(r.next());
        }
        execute("UPDATE products SET price=99.00 WHERE id=1");
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT unit_price FROM order_items WHERE order_id=900")) {
            assertTrue(r.next());
            assertEquals(new BigDecimal("12.50"), r.getBigDecimal(1));
        }
    }

    @Test @DisplayName("B7 — Item đầu hợp lệ, item sau thiếu stock rollback toàn order")
    void b07_rollsBackAllWrites() throws SQLException {
        createControl();
        assertThrows(Ex01_OrderTransaction.InsufficientStockException.class,
                () -> Ex01_OrderTransaction.create(fixture.dataSource(), 901, 1,
                        List.of(new Ex01_OrderTransaction.Line(1, 2), new Ex01_OrderTransaction.Line(2, 1))));
        assertUnchanged();
    }

    @Test @DisplayName("B7 — Product mất sau item hợp lệ rollback cả stock và items")
    void b07_missingProductRollsBack() throws SQLException {
        createControl();
        assertThrows(Ex01_OrderTransaction.InsufficientStockException.class,
                () -> Ex01_OrderTransaction.create(fixture.dataSource(), 901, 1,
                        List.of(new Ex01_OrderTransaction.Line(1, 1), new Ex01_OrderTransaction.Line(999, 1))));
        assertUnchanged();
    }

    @Test @DisplayName("B7 — Input rỗng, null, trùng và quantity ngoài 1–1000 không đổi stock")
    void b07_rejectsInvalidInputsWithoutWrites() throws SQLException {
        createControl();
        List<List<Ex01_OrderTransaction.Line>> invalid = Arrays.asList(null, List.of(),
                Arrays.asList((Ex01_OrderTransaction.Line) null),
                List.of(new Ex01_OrderTransaction.Line(1, 0)),
                List.of(new Ex01_OrderTransaction.Line(1, -1)),
                List.of(new Ex01_OrderTransaction.Line(3, 1001)),
                List.of(new Ex01_OrderTransaction.Line(1, 1), new Ex01_OrderTransaction.Line(1, 1)));
        for (var lines : invalid) {
            assertThrows(IllegalArgumentException.class,
                    () -> Ex01_OrderTransaction.create(fixture.dataSource(), 901, 1, lines));
            assertUnchanged();
        }
        Ex01_OrderTransaction.create(fixture.dataSource(), 902, 1,
                List.of(new Ex01_OrderTransaction.Line(3, 1000)));
        assertEquals(0, scalar("SELECT stock FROM products WHERE id=3"));
        assertEquals(1000, scalar("SELECT quantity FROM order_items WHERE order_id=902"));
    }

    @Test @DisplayName("B7 — SQLException giữ SQLSTATE; customer sai và order trùng không thành công")
    void b07_preservesSqlFailure() throws SQLException {
        createControl();
        var missingCustomer = assertThrows(SQLException.class,
                () -> Ex01_OrderTransaction.create(fixture.dataSource(), 901, 999,
                        List.of(new Ex01_OrderTransaction.Line(1, 1))));
        assertEquals("23503", missingCustomer.getSQLState());
        assertUnchanged();
        var duplicate = assertThrows(SQLException.class,
                () -> Ex01_OrderTransaction.create(fixture.dataSource(), 900, 1,
                        List.of(new Ex01_OrderTransaction.Line(1, 1))));
        assertEquals("23505", duplicate.getSQLState());
        assertUnchanged();
    }

    private void createControl() throws SQLException {
        Ex01_OrderTransaction.create(fixture.dataSource(), 900, 1,
                List.of(new Ex01_OrderTransaction.Line(1, 1)));
        assertEquals(1, scalar("SELECT count(*) FROM orders WHERE id=900"));
        assertEquals(1, scalar("SELECT count(*) FROM order_items WHERE order_id=900"));
        assertEquals(3, scalar("SELECT stock FROM products WHERE id=1"));
    }

    private void assertUnchanged() throws SQLException {
        assertEquals(1, scalar("SELECT count(*) FROM orders"));
        assertEquals(1, scalar("SELECT count(*) FROM order_items"));
        assertEquals(0, scalar("SELECT count(*) FROM orders WHERE id=901"));
        assertEquals(3, scalar("SELECT stock FROM products WHERE id=1"));
        assertEquals(0, scalar("SELECT stock FROM products WHERE id=2"));
        assertEquals(1000, scalar("SELECT stock FROM products WHERE id=3"));
    }

    private long scalar(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement(); var r = s.executeQuery(sql)) {
            assertTrue(r.next());
            return r.getLong(1);
        }
    }

    private void execute(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute(sql); }
    }
}
