package phase04.d03_sql_joins;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.math.BigDecimal;
import java.sql.SQLException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import phase04.support.PostgresFixture;

class Ex01_OrderHistoryQueryTest {
    private static PostgresFixture fixture;
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai'),(2,'An');
            INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4),(2,'Book',5.00,4);
            INSERT INTO orders(id,customer_id,status,created_at) VALUES (1,1,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00'),(2,1,'CANCELLED',TIMESTAMPTZ '2026-01-02 00:00:00+00');
            INSERT INTO order_items(order_id,product_id,quantity,unit_price) VALUES (1,1,2,10.00),(1,2,1,5.00),(2,1,1,12.00);
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q1 — Tự trả lời: LEFT JOIN")
    void q01_writtenAnswer() { assertTrue(true); }
    @Test @DisplayName("Q2 — Tự trả lời: kiểm tra NULL")
    void q02_writtenAnswer() { assertTrue(true); }
    @Test @DisplayName("Q3 — Tự trả lời: WHERE và HAVING")
    void q03_writtenAnswer() { assertTrue(true); }
    @Test @DisplayName("Q4 — Thí nghiệm: aggregate không nhân tổng")
    void q04_noDuplicateAggregate() throws SQLException { assertEquals(25, sqlTotal()); }
    @Test @DisplayName("Q5 — Tự trả lời: window function")
    void q05_writtenAnswer() { assertTrue(true); }

    @Test @DisplayName("B3 — Lịch sử theo khách và khách không có đơn")
    void b03_historyAndEmptyCustomerSummary() {
        var history = Ex01_OrderHistoryQuery.forCustomer(fixture.dataSource(), 1);
        assertEquals(2, history.size());
        assertEquals(2, history.get(0).itemCount());
        assertEquals(new BigDecimal("25.00"), history.get(0).total());
        assertEquals("NEW", history.get(0).status());
        assertEquals(0, Ex01_OrderHistoryQuery.forCustomer(fixture.dataSource(), 2).size());
        var summaries = Ex01_OrderHistoryQuery.allCustomers(fixture.dataSource());
        assertEquals(0, summaries.stream().filter(row -> row.customerId() == 2).findFirst().orElseThrow().orderCount());
    }

    private static int sqlTotal() throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement(); var rs = s.executeQuery("SELECT SUM(i.quantity*i.unit_price) FROM orders o JOIN order_items i ON i.order_id=o.id WHERE o.id=1")) {
            rs.next();
            return rs.getBigDecimal(1).intValueExact();
        }
    }
}
