package phase04.d16_migrations;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.sql.DataSource;
import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.migration.BaseJavaMigration;
import org.flywaydb.core.api.migration.Context;

/**
 * Migration PostgreSQL 18; USD cố định, không thêm cột currency.
 * <p>Nguồn: 04-database-persistence.md, mục 16. B16: tạo schema, nâng cấp dữ liệu cũ,
 * chạy lại history; không giả định rename/drop an toàn cho rolling deploy.
 * Q1 [TỰ TRẢ LỜI] Migration đem lại lợi ích nào so với sửa schema thủ công?
 * Cần trước: schema bốn bảng và transaction DDL. Bắt đầu: viết ANSWER Q1.
 * Tài liệu: https://documentation.red-gate.com/flyway/flyway-concepts/migrations
 * Debug: đối chiếu flyway_schema_history, không sửa migration đã áp dụng.
 * Hoàn thành: giải thích version, thứ tự, history và khả năng tái tạo DB.
 * Q2 [TỰ TRẢ LỜI] Vì sao migration rename/drop cột có thể phá deploy rolling?
 * Cần trước: app cũ/mới cùng tồn tại. Bắt đầu: viết trình tự expand/contract.
 * Tài liệu: https://www.postgresql.org/docs/18/sql-altertable.html
 * Debug: tìm SQL app cũ vẫn tham chiếu cột. Hoàn thành: nêu giới hạn rollout lab.
 * Q3 [TỰ TRẢ LỜI] H2 khác PostgreSQL ở những hành vi nào cần quan tâm?
 * Cần trước: SQLSTATE, MVCC, row lock. Bắt đầu: liệt kê khác biệt trong ANSWER Q3.
 * Tài liệu: https://www.postgresql.org/docs/18/transaction-iso.html
 * Debug: lưu server_version và plan thật. Hoàn thành: không dùng H2 thay test DB.
 * Q4 [CODE] Test concurrency cần chạy trên loại database nào để có giá trị?
 * Cần trước: connection riêng, conditional update. Bắt đầu: cài reserve, chạy q04.
 * Tài liệu: https://www.postgresql.org/docs/18/explicit-locking.html
 * Debug: gate trước lock, query/future có timeout. Hoàn thành: stock conservation PG18.
 * Q5 [CODE] Làm sao tránh test phụ thuộc dữ liệu từ lần chạy trước?
 * Cần trước: fixture disposable và unique name. Bắt đầu: cài insertCustomer, chạy q05.
 * Tài liệu: https://java.testcontainers.org/modules/databases/postgres/
 * Debug: reset schema riêng giữa test, không dùng DB dùng chung hay thứ tự test.
 * Hoàn thành: cùng seed unique chạy được sau hai lần reset; không che lỗi bằng ON CONFLICT.
 */
public class Ex01_MigrationCompatibility {
    /** Provided bootstrap: topic 16 alone registers and executes real Flyway migrations. */
    public static void migrate(DataSource ds) { migrate(ds, "2"); }

    public static void migrate(DataSource ds, String target) {
        if (ds == null || !("1".equals(target) || "2".equals(target)))
            throw new IllegalArgumentException("DataSource required; target 1 or 2");
        Flyway.configure().dataSource(ds).loggers("slf4j").locations(new String[0])
                .schemas("public").defaultSchema("public").cleanDisabled(true)
                .baselineOnMigrate(false)
                .javaMigrations(new V1__DomainSchema(), new V2__QuantityConstraint())
                .target(target).load().migrate();
    }

    public static class V1__DomainSchema extends BaseJavaMigration {
        @Override public void migrate(Context context) throws SQLException {
            try (var statement = context.getConnection().createStatement()) {
                statement.setQueryTimeout(10);
                for (String sql : schemaSql()) statement.execute(sql);
            }
        }
    }

    public static class V2__QuantityConstraint extends BaseJavaMigration {
        @Override public void migrate(Context context) throws SQLException {
            try (var statement = context.getConnection().createStatement()) {
                statement.setQueryTimeout(10);
                for (String sql : quantityConstraintSql()) statement.execute(sql);
            }
        }
    }

    static List<String> schemaSql() {
        // SOLUTION-BEGIN throw B16
        return List.of(
                "CREATE TABLE customers (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE)",
                "CREATE TABLE products (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE, price NUMERIC(19,2) NOT NULL CHECK (price >= 0), stock INTEGER NOT NULL CHECK (stock >= 0))",
                "CREATE TABLE orders (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id BIGINT NOT NULL REFERENCES customers(id), status TEXT NOT NULL CHECK (status IN ('NEW','CANCELLED')), created_at TIMESTAMP WITH TIME ZONE NOT NULL)",
                // V1 quantity is NOT NULL; V2 validates old rows before the final domain check.
                "CREATE TABLE order_items (id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL, unit_price NUMERIC(19,2) NOT NULL CHECK (unit_price >= 0), UNIQUE (order_id,product_id))");
        // SOLUTION-END
    }

    static List<String> quantityConstraintSql() {
        // SOLUTION-BEGIN throw B16
        // Preserve valid rows; fail closed for invalid old quantities, require explicit operator repair.
        return List.of(
                "ALTER TABLE order_items ADD CONSTRAINT order_items_quantity_range CHECK (quantity BETWEEN 1 AND 1000) NOT VALID",
                "ALTER TABLE order_items VALIDATE CONSTRAINT order_items_quantity_range");
        // SOLUTION-END
    }

    static boolean reserve(Connection c, long productId, int quantity) throws SQLException {
        // SOLUTION-BEGIN throw Q4
        if (c == null || productId <= 0 || quantity < 1 || quantity > 1000)
            throw new IllegalArgumentException("Connection/id required; quantity 1–1000");
        try (var s = c.prepareStatement("UPDATE products SET stock=stock-? WHERE id=? AND stock>=?")) {
            s.setQueryTimeout(10);
            s.setInt(1, quantity); s.setLong(2, productId); s.setInt(3, quantity);
            return s.executeUpdate() == 1;
        }
        // SOLUTION-END
    }

    static long insertCustomer(DataSource ds, String name) throws SQLException {
        // SOLUTION-BEGIN throw Q5
        if (ds == null || name == null || name.isBlank()) throw new IllegalArgumentException("DataSource/name required");
        try (var c = ds.getConnection(); var s = c.prepareStatement("INSERT INTO customers(name) VALUES (?) RETURNING id")) {
            s.setQueryTimeout(10); s.setString(1, name);
            try (var rows = s.executeQuery()) {
                if (!rows.next()) throw new SQLException("Customer insert returned no id");
                return rows.getLong(1);
            }
        }
        // SOLUTION-END
    }
}

/* ANSWER Q1:
 * SOLUTION-BEGIN
 * Version và history cho thứ tự xác định, áp dụng một lần, review/triển khai lặp lại trên DB rỗng.
 * Sửa tay gây drift giữa môi trường. Java migrations không mặc định checksum SQL như SQL migrations;
 * không sửa migration đã chạy, thêm version mới và giữ source trong Git.
 * SOLUTION-END
 */
/* ANSWER Q2:
 * SOLUTION-BEGIN
 * App cũ vẫn đọc/ghi tên cột cũ; rename/drop ngay gây lỗi khi app cũ và mới cùng chạy.
 * Expand thêm cấu trúc tương thích, chuyển/backfill/kiểm chứng dữ liệu, chuyển app, contract sau
 * khi app cũ ngừng. NOT VALID/VALIDATE vẫn có lock và scan; lab không chứng minh zero downtime.
 * SOLUTION-END
 */
/* ANSWER Q3:
 * SOLUTION-BEGIN
 * H2 không tái tạo MVCC/SSI, SQLSTATE deadlock, row lock, timestamptz, NUMERIC và planner PostgreSQL.
 * PostgreSQL 18.0 thật, connections riêng, deadline và invariant tạo bằng chứng đúng DB đích.
 * SOLUTION-END
 */
/* OBSERVATION B16 / ANSWER Q4,Q5:
 * SOLUTION-BEGIN
 * V1 tạo bốn bảng, quantity NOT NULL; V2 CHECK NOT VALID rồi VALIDATE trong transaction Flyway.
 * Row hợp lệ giữ id/quantity/price. Row cũ sai làm upgrade fail và rollback DDL; operator sửa
 * dữ liệu tường minh rồi migrate lại, không clamp quantity hoặc xóa order che mất dữ liệu.
 * Fixture class-local reset public trước mỗi test; hai contenders dùng connections riêng,
 * gate trước stock UPDATE, một accepted với stock=1, chạy lại migrate history vẫn hai version.
 * SOLUTION-END
 */
