package phase04.d02_constraints;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;

import java.sql.SQLException;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import phase04.support.PostgresFixture;

class Ex01_DataConstraintsTest {
    private static PostgresFixture fixture;
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = "INSERT INTO customers(id,name) VALUES (1,'Mai'); INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4); INSERT INTO orders(id,customer_id,status,created_at) VALUES (1,1,'NEW',CURRENT_TIMESTAMP);";

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q2 — Code: quantity lớn hơn 0")
    void q02_experimentRuns() throws SQLException {
        assertSqlState("23514", () -> insertItem("quantity,unit_price", "0,12.50"));
    }

    @Test @DisplayName("Q5 — Thí nghiệm: explicit NULL và default")
    void q05_experimentRuns() throws SQLException {
        assertSqlState("23502", () -> insertOrder("NULL", "CURRENT_TIMESTAMP"));
        assertSqlState("23514", () -> update("UPDATE products SET price=-1 WHERE id=1"));
    }

    @Test @DisplayName("B2 — DB từ chối giá, quantity, trạng thái và tồn kho sai")
    void b02_experimentRuns() throws SQLException {
        assertSqlState("23514", () -> update("UPDATE products SET price=-1 WHERE id=1"));
        assertSqlState("23514", () -> update("UPDATE products SET stock=-1 WHERE id=1"));
        assertSqlState("23514", () -> update("UPDATE orders SET status='UNKNOWN' WHERE id=1"));
        assertSqlState("23514", () -> insertItem("quantity,unit_price", "1001,12.50"));
    }

    private static void insertItem(String columns, String values) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            s.executeUpdate("INSERT INTO order_items(order_id,product_id," + columns + ") VALUES (1,1," + values + ")");
        }
    }

    private static void insertOrder(String customerId, String createdAt) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            s.executeUpdate("INSERT INTO orders(customer_id,status,created_at) VALUES (" + customerId + ",'NEW'," + createdAt + ")");
        }
    }

    private static void update(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.executeUpdate(sql); }
    }

    private static void assertSqlState(String state, SqlAction action) {
        SQLException failure = assertThrows(SQLException.class, action::run);
        assertEquals(state, failure.getSQLState());
    }

    @FunctionalInterface private interface SqlAction { void run() throws SQLException; }
}
