package phase04.d08_isolation;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_IsolationAnomalyTest {
    private static PostgresFixture fixture;
    // Provided independent four-table schema; no d01 learner migrations.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = "INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',1.00,1),(2,'Book',1.00,1)";
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("B8 — Write skew thật trên hai hàng; Serializable báo 40001")
    void b08_writeSkewAndSerializable() throws SQLException {
        for (var level : Ex01_IsolationAnomaly.IsolationLevel.values()) {
            fixture.reset(SCHEMA, SEED);
            var observation = Ex01_IsolationAnomaly.run(fixture.dataSource(), level);
            System.out.println("B8 " + level + " " + observation);
            assertEquals(2, observation.events().stream().filter(e -> e.contains("read=2")).count());
            boolean serializable = level == Ex01_IsolationAnomaly.IsolationLevel.SERIALIZABLE;
            assertEquals(serializable, observation.invariantHeld());
            assertEquals(serializable ? 1 : 0, scalar("SELECT sum(stock) FROM products"));
            assertEquals(serializable ? 1 : 0,
                    observation.events().stream().filter(e -> e.contains("40001")).count());
            assertEquals(serializable ? 1 : 2,
                    observation.events().stream().filter(e -> e.endsWith("commit")).count());
        }
    }

    @Test @DisplayName("Q1/Q2/Q3 — Thí nghiệm được cung cấp: không dirty read, snapshot và phantom")
    void q01_q02_q03_snapshot_experimentRuns() throws SQLException {
        // Human ANSWER Q1–Q3 in main source; this provided experiment is not a prose grader.
        for (var level : Ex01_IsolationAnomaly.IsolationLevel.values()) {
            fixture.reset(SCHEMA, SEED);
            try (var reader = fixture.dataSource().getConnection(); var writer = fixture.dataSource().getConnection()) {
                reader.setTransactionIsolation(level.jdbc);
                reader.setAutoCommit(false);
                writer.setAutoCommit(false);
                try {
                    execute(writer, "UPDATE products SET stock=7 WHERE id=1");
                    assertEquals(1, stock(reader)); // Uncommitted writer invisible even at RU.
                    assertEquals(2, count(reader));
                    execute(writer, "INSERT INTO products(id,name,price,stock) VALUES (3,'New',1.00,1)");
                    writer.commit(); // Gate: next reader statement only after actual writer commit.
                    boolean fresh = level == Ex01_IsolationAnomaly.IsolationLevel.READ_COMMITTED
                            || level == Ex01_IsolationAnomaly.IsolationLevel.READ_UNCOMMITTED;
                    assertEquals(fresh ? 7 : 1, stock(reader));
                    assertEquals(fresh ? 3 : 2, count(reader));
                } finally { reader.rollback(); writer.rollback(); }
            }
            assertEquals(7, scalar("SELECT stock FROM products WHERE id=1"));
            assertEquals(3, scalar("SELECT count(*) FROM products"));
        }
    }

    @Test @DisplayName("Q5 — Hai request cùng product bảo toàn stock qua connection thứ ba")
    void q05_sameProductConservesStock() throws Exception {
        try (var c = fixture.dataSource().getConnection()) {
            c.setAutoCommit(false);
            try { assertTrue(Ex01_IsolationAnomaly.reserve(c, 1, 1)); }
            finally { c.rollback(); }
        } // Valid marked control before workers: stripped TODO cannot strand peer at barrier.
        assertEquals(1, scalar("SELECT stock FROM products WHERE id=1"));
        var gate = new CyclicBarrier(2);
        var pool = Executors.newFixedThreadPool(2);
        var futures = new ArrayList<Future<Boolean>>();
        try {
            for (int i = 0; i < 2; i++) futures.add(pool.submit(() -> {
                try (var c = fixture.dataSource().getConnection()) {
                    c.setAutoCommit(false);
                    try {
                        gate.await(5, TimeUnit.SECONDS);
                        boolean accepted = Ex01_IsolationAnomaly.reserve(c, 1, 1);
                        c.commit();
                        return accepted;
                    } finally { c.rollback(); }
                }
            }));
            int sold = 0;
            for (var future : futures) if (future.get(15, TimeUnit.SECONDS)) sold++;
            long remaining = scalar("SELECT stock FROM products WHERE id=1");
            assertEquals(1, sold);
            assertEquals(1, sold + remaining);
            assertTrue(remaining >= 0);
        } finally {
            futures.forEach(f -> f.cancel(true));
            pool.shutdownNow();
            assertTrue(pool.awaitTermination(5, TimeUnit.SECONDS));
        }
    }

    private static void execute(Connection c, String sql) throws SQLException {
        try (var s = c.createStatement()) { s.setQueryTimeout(10); s.execute(sql); }
    }
    private static long stock(Connection c) throws SQLException { return scalar(c, "SELECT stock FROM products WHERE id=1"); }
    private static long count(Connection c) throws SQLException { return scalar(c, "SELECT count(*) FROM products"); }
    private long scalar(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection()) { return scalar(c, sql); }
    }
    private static long scalar(Connection c, String sql) throws SQLException {
        try (var s = c.createStatement()) {
            s.setQueryTimeout(10);
            try (var r = s.executeQuery(sql)) { assertTrue(r.next()); return r.getLong(1); }
        }
    }
}
