package phase04.d11_entity_lifecycle;

import static org.junit.jupiter.api.Assertions.*;

import jakarta.persistence.EntityManagerFactory;
import java.sql.SQLException;
import org.hibernate.cfg.Configuration;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_EntityLifecycleTest {
    private static PostgresFixture fixture;
    private EntityManagerFactory emf;
    // Provided Task 1 schema, independent of lifecycle learner code. Currency: USD.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai');
            INSERT INTO orders(id,customer_id,status,created_at) VALUES (100,1,'NEW','2026-01-01T00:00:00Z');
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException {
        fixture.reset(SCHEMA, SEED);
        // Provided bootstrap: explicit class, no scanning, no generated answer schema.
        emf = bootstrap();
    }
    private EntityManagerFactory bootstrap() {
        var config = new Configuration().addAnnotatedClass(Ex01_EntityLifecycle.Order.class)
                .setProperty("hibernate.hbm2ddl.auto", "validate")
                .setProperty("hibernate.jdbc.time_zone", "UTC");
        config.getProperties().put("hibernate.connection.datasource", fixture.dataSource());
        return config.buildSessionFactory();
    }
    @AfterEach void closeMapping() { if (emf != null) emf.close(); }

    @Test @DisplayName("B11 — Flush không commit, merge trả instance managed, không rò hàng mới")
    void b11_observesLifecycleWithCommittedRowProof() throws SQLException {
        var seen = Ex01_EntityLifecycle.observe(emf, 100);
        assertTrue(seen.managedBeforeFlush());
        assertFalse(seen.rowVisibleBeforeCommit());
        assertTrue(seen.mergeReturnedManaged());
        assertEquals("NEW", status(100));
        assertEquals(1, orderCount());
        System.out.println("B11: fresh JDBC status=NEW, orders=1; before commit inserted row invisible");
    }

    @Test @DisplayName("Q2 — Dirty checking ghi thay đổi managed khi flush, không cần merge")
    void q02_dirtyCheckingWritesAtCommit() throws SQLException {
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            Ex01_EntityLifecycle.cancel(em, 100); // TODO must fail outside assertThrows.
            assertTrue(em.contains(em.find(Ex01_EntityLifecycle.Order.class, 100L)));
            em.flush();
            assertEquals("NEW", status(100));
            em.getTransaction().commit();
        }
        assertEquals("CANCELLED", status(100));
    }

    @Test @DisplayName("Q3 — Merge dùng bản sao managed; bản gốc vẫn detached")
    void q03_mergeReturnsDifferentManagedInstance() throws SQLException {
        Ex01_EntityLifecycle.Order detached;
        try (var em = emf.createEntityManager()) {
            detached = em.find(Ex01_EntityLifecycle.Order.class, 100L);
            em.detach(detached);
            assertFalse(em.contains(detached));
        }
        detached.status = "CANCELLED";
        assertEquals("NEW", status(100));
        try (var em = emf.createEntityManager()) {
            em.getTransaction().begin();
            var managed = Ex01_EntityLifecycle.mergeDetached(em, detached);
            assertNotSame(detached, managed);
            assertTrue(em.contains(managed));
            assertFalse(em.contains(detached));
            managed.status = "NEW";
            detached.status = "CANCELLED";
            em.getTransaction().commit();
        }
        assertEquals("NEW", status(100));
    }

    @Test @DisplayName("B11 — Đối chiếu transient, managed, detached, removed và rollback")
    void b11_states_experimentRuns() throws SQLException {
        // Provided experiment only; learner CODE is assessed by q02/q03 and observe.
        try (var em = emf.createEntityManager()) {
            var order = new Ex01_EntityLifecycle.Order(1, java.time.Instant.parse("2026-02-01T00:00:00Z"));
            assertNull(order.id);
            assertFalse(em.contains(order));
            em.getTransaction().begin();
            em.persist(order);
            assertTrue(em.contains(order));
            // Native connection inspection avoids query-triggered automatic flush.
            long rowsBeforeExplicitFlush = em.unwrap(org.hibernate.Session.class).doReturningWork(c -> {
                try (var s = c.createStatement(); var rows = s.executeQuery("SELECT count(*) FROM orders")) {
                    rows.next();
                    return rows.getLong(1);
                }
            });
            assertEquals(2, rowsBeforeExplicitFlush); // IDENTITY INSERT occurred at persist.
            assertEquals(1, orderCount());
            em.flush();
            long id = order.id;
            assertEquals(1, orderCount());
            em.getTransaction().commit();
            assertEquals(2, orderCount());
            em.detach(order);
            assertFalse(em.contains(order));
            order.status = "CANCELLED";
            em.getTransaction().begin();
            em.flush();
            em.getTransaction().commit();
            assertEquals("NEW", status(id));
            em.getTransaction().begin();
            var managed = em.find(Ex01_EntityLifecycle.Order.class, id);
            em.remove(managed);
            assertFalse(em.contains(managed));
            em.flush();
            assertEquals(2, orderCount());
            em.getTransaction().commit();
            assertEquals(1, orderCount());
            assertNull(em.find(Ex01_EntityLifecycle.Order.class, id));
        }
    }

    @Test @DisplayName("B11 — Kiểm tra đầu vào sau positive control")
    void b11_rejectsMissingOrderAndNullFactory() {
        assertTrue(Ex01_EntityLifecycle.observe(emf, 100).mergeReturnedManaged());
        assertThrows(IllegalArgumentException.class, () -> Ex01_EntityLifecycle.observe(emf, 0));
        assertThrows(IllegalArgumentException.class, () -> Ex01_EntityLifecycle.observe(emf, 999));
        assertThrows(IllegalArgumentException.class, () -> Ex01_EntityLifecycle.observe(null, 100));
    }

    private static String status(long id) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.prepareStatement("SELECT status FROM orders WHERE id=?")) {
            s.setLong(1, id);
            try (var rows = s.executeQuery()) { return rows.next() ? rows.getString(1) : null; }
        }
    }
    private static long orderCount() throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var rows = s.executeQuery("SELECT count(*) FROM orders")) {
            rows.next();
            return rows.getLong(1);
        }
    }
}
