package phase04.d05_explain;

import java.sql.SQLException;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;
import static org.junit.jupiter.api.Assertions.*;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_QueryPlanTest {
    // Provided bootstrap: no learner EXPLAIN query; no dependency on B1 migrations.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE,
              price NUMERIC(19,2) NOT NULL CHECK(price >= 0), stock INTEGER NOT NULL CHECK(stock >= 0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              customer_id BIGINT NOT NULL REFERENCES customers(id), status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),
              created_at TIMESTAMP WITH TIME ZONE NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id),
              quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000), unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price >= 0),
              UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) SELECT n,'Customer ' || n FROM generate_series(1,100) n;
            INSERT INTO orders(id,customer_id,status,created_at)
            SELECT n,1 + n % 100,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00' + n * INTERVAL '1 second'
            FROM generate_series(1,20000) n;
            ANALYZE orders;
            """;
    private static PostgresFixture fixture;
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("B5 — lưu EXPLAIN ANALYZE BUFFERS thực tế trước/sau thay đổi")
    void b05_realPlansAndReadOnlyWorkload() throws SQLException {
        String before = Ex01_QueryPlan.explain(fixture.dataSource(), 1L);
        assertPlan(before);
        assertEquals(20000, countOrders());
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            // Provided tuning intervention, not learner EXPLAIN SQL.
            s.execute("CREATE INDEX provided_plan_history ON orders(customer_id,created_at,id)");
            s.execute("ANALYZE orders");
        }
        String after = Ex01_QueryPlan.explain(fixture.dataSource(), 1L);
        assertPlan(after);
        assertEquals(20000, countOrders());
        System.out.println("B5 dataset=20000 orders/100 customers; customer 1=200 orders; SELECT only.\nBefore:\n"
                + before + "\nAfter:\n" + after);
        // Human inspects expensive node and estimated/actual rows; no chosen node/time golden.
    }

    @Test @DisplayName("B5 — customer predicate bind và SQL lỗi không bị nuốt")
    void b05_customerScopeAndSqlErrors() throws SQLException {
        String present = Ex01_QueryPlan.explain(fixture.dataSource(), 1L);
        assertPlan(present); // positive control before invalid checks
        assertThrows(IllegalArgumentException.class, () -> Ex01_QueryPlan.explain(null, 1L));
        assertThrows(IllegalArgumentException.class, () -> Ex01_QueryPlan.explain(fixture.dataSource(), 0L));
        assertThrows(IllegalArgumentException.class, () -> Ex01_QueryPlan.explain(fixture.dataSource(), -1L));
        String absent = Ex01_QueryPlan.explain(fixture.dataSource(), 999L);
        assertPlan(absent);
        assertTrue(present.contains("customer_id"));
        assertTrue(absent.contains("999"), "Plan hiển thị giá trị customer đã bind");
        assertTrue(absent.matches("(?s).*actual [^\\n]*rows=0(?:\\.0+)? loops=1.*"),
                "Customer thiếu trả 0 hàng thực tế:\n" + absent);
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute("DROP TABLE orders CASCADE"); }
        IllegalStateException failure = assertThrows(IllegalStateException.class,
                () -> Ex01_QueryPlan.explain(fixture.dataSource(), 1L));
        SQLException cause = assertInstanceOf(SQLException.class, failure.getCause());
        assertEquals("42P01", cause.getSQLState());
    }

    private static void assertPlan(String plan) {
        assertFalse(plan.isBlank());
        assertTrue(plan.contains("actual") && plan.contains("Buffers"));
        assertTrue(plan.contains("Planning Time") && plan.contains("Execution Time"));
    }
    private long countOrders() throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT COUNT(*) FROM orders")) { r.next(); return r.getLong(1); }
    }
}
