package phase04.d14_locking;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.concurrent.*;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_StockLockingTest {
    private static PostgresFixture fixture;
    // Independent provided schema. Version added only for explicitly local optimistic comparison.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = "INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',1.00,1),(2,'Bulk',1.00,1000)";
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q2 — Affected count, caller rollback và quantity hợp lệ 1–1000")
    void q02_affectedRowsAndValidation() throws SQLException {
        control(0);
        try (var c = fixture.dataSource().getConnection()) {
            c.setAutoCommit(false);
            try {
                assertTrue(Ex01_StockLocking.reserve(c, 1, 1));
                assertFalse(Ex01_StockLocking.reserve(c, 1, 1));
                assertFalse(Ex01_StockLocking.reserve(c, 999, 1));
                assertTrue(Ex01_StockLocking.reserve(c, 2, 1000));
                for (int q : new int[]{-1, 0, 1001})
                    assertThrows(IllegalArgumentException.class, () -> Ex01_StockLocking.reserve(c, 1, q));
                assertThrows(IllegalArgumentException.class, () -> Ex01_StockLocking.reserve(c, 0, 1));
                c.rollback();
            } finally { c.rollback(); }
        }
        assertEquals(1, scalar("SELECT stock FROM products WHERE id=1"));
        assertEquals(1000, scalar("SELECT stock FROM products WHERE id=2"));
        // SQL-looking DB failure cannot be confused with TODO: control already succeeded.
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            s.setQueryTimeout(10);
            var error = assertThrows(SQLException.class, () -> s.executeUpdate("UPDATE products SET stock=-1 WHERE id=1"));
            assertEquals("23514", error.getSQLState());
        }
    }

    @Test @DisplayName("Q5/B14 — Hai TX conditional update không oversell, conservation")
    void q05_b14_conditionalConservation() throws Exception { contend(0); }

    @Test @DisplayName("B14 — Optimistic cùng version, chỉ một writer cập nhật")
    void b14_optimisticConflict() throws Exception {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            s.execute("ALTER TABLE products ADD COLUMN version INTEGER NOT NULL DEFAULT 0");
        }
        contend(1);
        assertEquals(1, scalar("SELECT version FROM products WHERE id=1"));
    }

    @Test @DisplayName("B14 — Pessimistic row lock đọc lại stock sau peer commit")
    void b14_pessimisticConservation() throws Exception { contend(2); }

    private void control(int mode) throws SQLException {
        try (var c = fixture.dataSource().getConnection()) {
            c.setAutoCommit(false);
            try { assertTrue(reserve(c, mode, 0)); }
            finally { c.rollback(); }
        }
        assertEquals(1, scalar("SELECT stock FROM products WHERE id=1"));
    }

    private void contend(int mode) throws Exception {
        control(mode); // TODO surfaces before worker gates, not disguised as barrier timeout.
        var gate = new CyclicBarrier(2);
        var pool = Executors.newFixedThreadPool(2);
        var futures = new ArrayList<Future<Boolean>>();
        try {
            for (int i = 0; i < 2; i++) futures.add(pool.submit(() -> {
                try (var c = fixture.dataSource().getConnection()) {
                    c.setAutoCommit(false);
                    try {
                        int version = 0;
                        try (var s = c.createStatement()) {
                            s.setQueryTimeout(10);
                            s.execute("SET LOCAL lock_timeout='5s'");
                            if (mode == 1) try (var r = s.executeQuery("SELECT version FROM products WHERE id=1")) {
                                assertTrue(r.next()); version = r.getInt(1);
                            }
                        }
                        gate.await(5, TimeUnit.SECONDS); // Before contested lock, both versions read.
                        boolean accepted = reserve(c, mode, version);
                        c.commit();
                        return accepted;
                    } finally { c.rollback(); }
                }
            }));
            int accepted = 0;
            for (var f : futures) if (f.get(15, TimeUnit.SECONDS)) accepted++;
            long remaining = scalar("SELECT stock FROM products WHERE id=1");
            System.out.println("B14 mode=" + mode + " accepted=" + accepted + " remaining=" + remaining);
            assertEquals(1, accepted);
            assertTrue(accepted <= 1);
            assertTrue(remaining >= 0);
            assertEquals(1, accepted + remaining);
        } finally {
            futures.forEach(f -> f.cancel(true));
            pool.shutdownNow();
            assertTrue(pool.awaitTermination(12, TimeUnit.SECONDS));
        }
    }

    private static boolean reserve(Connection c, int mode, int version) throws SQLException {
        return switch (mode) {
            case 0 -> Ex01_StockLocking.reserve(c, 1, 1);
            case 1 -> Ex01_StockLocking.reserveOptimistic(c, 1, 1, version);
            case 2 -> Ex01_StockLocking.reservePessimistic(c, 1, 1);
            default -> throw new IllegalArgumentException("Unknown comparison");
        };
    }
    private long scalar(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) {
            s.setQueryTimeout(10);
            try (var r = s.executeQuery(sql)) { assertTrue(r.next()); return r.getLong(1); }
        }
    }
}
