package phase04.d06_pagination;

import java.sql.SQLException;
import java.time.Instant;
import java.util.List;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;
import static org.junit.jupiter.api.Assertions.*;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_OrderPageTest {
    // Fixed independent bootstrap; neither paging SQL nor B1 learner migrations.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL UNIQUE,
              price NUMERIC(19,2) NOT NULL CHECK(price >= 0), stock INTEGER NOT NULL CHECK(stock >= 0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              customer_id BIGINT NOT NULL REFERENCES customers(id), status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),
              created_at TIMESTAMP WITH TIME ZONE NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id BIGINT NOT NULL REFERENCES products(id),
              quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000), unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price >= 0),
              UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES(1,'Mai'),(2,'An'),(3,'Chưa có đơn');
            INSERT INTO orders(id,customer_id,status,created_at) VALUES
              (1,1,'NEW','2026-01-01 00:00:10+00'),(2,1,'CANCELLED','2026-01-01 00:00:20+00'),
              (3,1,'NEW','2026-01-01 00:00:30+00'),(4,1,'NEW','2026-01-01 00:00:40+00'),
              (99,2,'NEW','2026-01-01 00:00:15+00');
            """;
    private static final Instant T0 = Instant.parse("2026-01-01T00:00:00Z");
    private static final Instant T20 = Instant.parse("2026-01-01T00:00:20Z");
    private static PostgresFixture fixture;
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("B6 — page zero-based, tie timestamp ổn định và customer scope")
    void b06_usesStableZeroBasedPages() throws SQLException {
        execute("UPDATE orders SET created_at = '2026-01-01 00:00:20+00' WHERE id = 1");
        var first = Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 1);
        assertEquals(List.of(1L), ids(first));
        assertEquals(List.of(2L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 1, 1)));
        assertEquals(List.of(2L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 1L, 1)));
        assertEquals(new Ex01_OrderPage.OrderRow(1L, T20, "NEW"), first.getFirst());
        assertEquals("CANCELLED", Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 1, 1).getFirst().status());
        assertEquals(List.of(99L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 2L, 0, 100)));
        assertEquals(List.of(99L), ids(Ex01_OrderPage.after(fixture.dataSource(), 2L, T0, 1L, 100)));
        assertThrows(UnsupportedOperationException.class, first::clear);
        var cursorRows = Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 1L, 2);
        assertEquals(List.of(2L, 3L), ids(cursorRows));
        assertThrows(UnsupportedOperationException.class, cursorRows::clear);
    }

    @Test @DisplayName("B6/Q4 — insert trước cursor lặp offset nhưng không lặp keyset")
    void b06_insertBetweenRequests() throws SQLException {
        assertEquals(List.of(1L, 2L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 2)));
        var first = Ex01_OrderPage.after(fixture.dataSource(), 1L, T0, 1L, 2);
        assertEquals(List.of(1L, 2L), ids(first));
        var cursor = first.getLast();
        assertEquals(T20, cursor.createdAt());
        execute("INSERT INTO orders(id,customer_id,status,created_at) VALUES(5,1,'NEW','2026-01-01 00:00:15+00')");
        var offsetNext = ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 1, 2));
        var cursorNext = ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, cursor.createdAt(), cursor.id(), 2));
        assertEquals(List.of(2L, 3L), offsetNext);
        assertEquals(List.of(3L, 4L), cursorNext);
        System.out.println("B6/Q4 initial=[1,2]; insert=(5,t15); offset page1=" + offsetNext
                + "; after(t20,2)=" + cursorNext + "; keyset không phải global snapshot.");
    }

    @Test @DisplayName("B6 — keyset strict tuple, timestamp microsecond và không có global snapshot")
    void b06_strictTupleAndLaterInsert() throws SQLException {
        execute("INSERT INTO orders(id,customer_id,status,created_at) VALUES"
                + "(5,1,'NEW','2026-01-01 00:00:20+00'),(6,1,'NEW','2026-01-01 00:00:20.000001+00')");
        assertEquals(List.of(5L, 6L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 2L, 2)));
        var last = Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 5L, 1).getFirst();
        assertEquals(T20.plusNanos(1000), last.createdAt());
        assertEquals(List.of(3L, 4L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, last.createdAt(), 6L, 2)));
        execute("INSERT INTO orders(id,customer_id,status,created_at) VALUES(7,1,'NEW','2026-01-01 00:00:25+00')");
        assertEquals(List.of(7L, 3L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, last.createdAt(), 6L, 2)));
    }

    @Test @DisplayName("B6 — size 1..100, page >=0 và offset tính bằng checked long")
    void b06_validatesPageAndSize() {
        assertEquals(List.of(1L, 2L, 3L, 4L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 100)));
        assertEquals(List.of(1L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, T0, 1L, 1)));
        assertEquals(List.of(), Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, Integer.MAX_VALUE, 100));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, -1, 2));
        for (int size : new int[]{-1, 0, 101, Integer.MAX_VALUE}) {
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, size));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.after(fixture.dataSource(), 1L, T0, 1L, size));
        }
    }

    @Test @DisplayName("B6 — customer/cursor ID dương, DataSource/time không null")
    void b06_validatesTrustBoundary() {
        assertEquals(List.of(3L, 4L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 2L, 2)));
        assertEquals(List.of(1L, 2L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 2)));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.offsetPage(null, 1L, 0, 2));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.after(null, 1L, T20, 2L, 2));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.after(fixture.dataSource(), 1L, null, 2L, 2));
        for (long id : new long[]{0L, -1L}) {
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.offsetPage(fixture.dataSource(), id, 0, 2));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.after(fixture.dataSource(), id, T20, 2L, 2));
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, id, 2));
        }
    }

    @Test @DisplayName("B6 — trang cuối, khách chưa có đơn và khách thiếu đều trả list rỗng")
    void b06_emptyPagesAndMissingCustomers() {
        assertEquals(List.of(3L, 4L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 1, 2)));
        assertEquals(List.of(), Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 2, 2));
        assertEquals(List.of(), Ex01_OrderPage.after(fixture.dataSource(), 1L, Instant.parse("2026-01-01T00:00:40Z"), 4L, 2));
        for (long customer : new long[]{3L, 999L}) {
            assertEquals(List.of(), Ex01_OrderPage.offsetPage(fixture.dataSource(), customer, 0, 2));
            assertEquals(List.of(), Ex01_OrderPage.after(fixture.dataSource(), customer, T0, 1L, 2));
        }
    }

    @Test @DisplayName("B6 — SQL lỗi giữ SQLException gốc, không giả thành trang rỗng")
    void b06_preservesSqlErrors() throws SQLException {
        assertEquals(List.of(1L, 2L), ids(Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 2)));
        assertEquals(List.of(3L, 4L), ids(Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 2L, 2)));
        execute("DROP TABLE orders CASCADE");
        var offsetError = assertThrows(IllegalStateException.class, () -> Ex01_OrderPage.offsetPage(fixture.dataSource(), 1L, 0, 2));
        var cursorError = assertThrows(IllegalStateException.class, () -> Ex01_OrderPage.after(fixture.dataSource(), 1L, T20, 2L, 2));
        assertEquals("42P01", assertInstanceOf(SQLException.class, offsetError.getCause()).getSQLState());
        assertEquals("42P01", assertInstanceOf(SQLException.class, cursorError.getCause()).getSQLState());
    }

    private static List<Long> ids(List<Ex01_OrderPage.OrderRow> rows) { return rows.stream().map(Ex01_OrderPage.OrderRow::id).toList(); }
    private void execute(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute(sql); }
    }
}
