package phase04.d15_deadlocks;

import static org.junit.jupiter.api.Assertions.*;

import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicInteger;
import org.junit.jupiter.api.*;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_DeadlockRetryTest {
    private static PostgresFixture fixture;
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = "INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',1.00,1),(2,'Book',1.00,1)";
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void stop() { if (fixture != null) fixture.close(); }
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q2 — Retry toàn transaction với connection và read state mới")
    void q02_freshTransactionAndRollback() throws SQLException {
        control();
        var connections = new ArrayList<Connection>();
        var backends = new ArrayList<Long>();
        var reads = new ArrayList<Long>();
        int result = Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 2, c -> {
            assertFalse(c.getAutoCommit());
            connections.add(c);
            backends.add(scalar(c, "SELECT pg_backend_pid()"));
            reads.add(scalar(c, "SELECT stock FROM products WHERE id=1"));
            execute(c, "UPDATE products SET stock=stock+10 WHERE id=1");
            if (connections.size() == 1) throw new SQLException("typed retry fault", "40001");
            return 42;
        });
        assertEquals(42, result);
        assertEquals(List.of(1L, 1L), reads);
        assertNotSame(connections.get(0), connections.get(1));
        assertNotEquals(backends.get(0), backends.get(1));
        for (var c : connections) assertTrue(c.isClosed());
        assertEquals(11, scalar("SELECT stock FROM products WHERE id=1"));
    }

    @Test @DisplayName("Q4 — Budget 1–10, SQLSTATE exact, Runtime/Error và rollback")
    void q04_boundedClassifierAndFailures() throws SQLException {
        control();
        for (int attempts : new int[]{0, -1, 11, Integer.MAX_VALUE})
            assertThrows(IllegalArgumentException.class,
                    () -> Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), attempts, c -> 0));
        for (String state : new String[]{"40001", "40P01", "23514", "55P03", "57014", "08006", null}) {
            var calls = new AtomicInteger();
            var primary = new SQLException("40001 in message is not classification", state);
            var failure = assertThrows(SQLException.class, () ->
                    Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 3, c -> {
                        calls.incrementAndGet();
                        execute(c, "UPDATE products SET stock=stock+1 WHERE id=1");
                        throw primary;
                    }));
            assertSame(primary, failure);
            assertEquals("40001".equals(state) || "40P01".equals(state) ? 3 : 1, calls.get());
            assertEquals(1, scalar("SELECT stock FROM products WHERE id=1"));
        }
        var calls = new AtomicInteger();
        var runtime = new IllegalStateException("business failure");
        assertSame(runtime, assertThrows(IllegalStateException.class, () ->
                Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 3, c -> {
                    calls.incrementAndGet(); execute(c, "UPDATE products SET stock=8 WHERE id=1"); throw runtime;
                })));
        var error = new AssertionError("work error");
        assertSame(error, assertThrows(AssertionError.class, () ->
                Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 3, c -> {
                    calls.incrementAndGet(); execute(c, "UPDATE products SET stock=9 WHERE id=1"); throw error;
                })));
        assertEquals(2, calls.get());
        assertEquals(1, scalar("SELECT stock FROM products WHERE id=1"));
        try {
            Thread.currentThread().interrupt();
            var failure = assertThrows(SQLException.class, () ->
                    Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 3, c -> {
                        fail("Interrupted caller must not start work"); return 0;
                    }));
            assertEquals("HY008", failure.getSQLState());
            assertTrue(Thread.currentThread().isInterrupted());
        } finally { Thread.interrupted(); }
    }

    @Test @DisplayName("B15 — Commit lỗi typed retry, rollback lỗi giữ primary suppressed")
    void b15_commitAndRollbackFailurePreservation() throws SQLException {
        control();
        var commits = new AtomicInteger();
        var rollbacks = new AtomicInteger();
        var opens = new AtomicInteger();
        var workCalls = new AtomicInteger();
        var primary = new SQLException("commit serialization failure", "40001");
        var cleanup = new SQLException("rollback diagnostic failure", "08006");
        var ds = (javax.sql.DataSource) java.lang.reflect.Proxy.newProxyInstance(
                getClass().getClassLoader(), new Class<?>[]{javax.sql.DataSource.class}, (proxy, method, args) -> {
                    if (!method.getName().equals("getConnection"))
                        throw new UnsupportedOperationException("Only getConnection used by lab");
                    opens.incrementAndGet();
                    var real = fixture.dataSource().getConnection();
                    return java.lang.reflect.Proxy.newProxyInstance(getClass().getClassLoader(),
                            new Class<?>[]{Connection.class}, (connection, operation, arguments) -> {
                                if (operation.getName().equals("commit") && commits.incrementAndGet() == 1)
                                    throw primary;
                                if (operation.getName().equals("rollback")) {
                                    rollbacks.incrementAndGet();
                                    real.rollback();
                                    throw cleanup;
                                }
                                try { return operation.invoke(real, arguments); }
                                catch (java.lang.reflect.InvocationTargetException failure) { throw failure.getCause(); }
                            });
                });
        int result = Ex01_DeadlockRetry.retryTransaction(ds, 2, c -> {
            workCalls.incrementAndGet();
            assertEquals(1, scalar(c, "SELECT stock FROM products WHERE id=1"));
            execute(c, "UPDATE products SET stock=stock+1 WHERE id=1");
            return 19;
        });
        assertEquals(19, result);
        assertEquals(2, opens.get());
        assertEquals(2, commits.get());
        assertEquals(2, workCalls.get());
        assertEquals(1, rollbacks.get());
        assertArrayEquals(new Throwable[]{cleanup}, primary.getSuppressed());
        assertEquals(2, scalar("SELECT stock FROM products WHERE id=1"));
    }

    @Test @DisplayName("B15 — Close lỗi sau commit thành công không replay transaction")
    void b15_neverRetriesSuccessfulCommitCloseFailure() throws SQLException {
        control();
        var calls = new AtomicInteger();
        var closeFailure = new SQLException("close failure, not transaction abort", "40001");
        var ds = (javax.sql.DataSource) java.lang.reflect.Proxy.newProxyInstance(
                getClass().getClassLoader(), new Class<?>[]{javax.sql.DataSource.class}, (proxy, method, args) -> {
                    var real = fixture.dataSource().getConnection();
                    return java.lang.reflect.Proxy.newProxyInstance(getClass().getClassLoader(),
                            new Class<?>[]{Connection.class}, (connection, operation, arguments) -> {
                                if (operation.getName().equals("close")) { real.close(); throw closeFailure; }
                                try { return operation.invoke(real, arguments); }
                                catch (java.lang.reflect.InvocationTargetException failure) { throw failure.getCause(); }
                            });
                });
        assertSame(closeFailure, assertThrows(SQLException.class, () ->
                Ex01_DeadlockRetry.retryTransaction(ds, 3, c -> {
                    calls.incrementAndGet();
                    execute(c, "UPDATE products SET stock=stock+1 WHERE id=1");
                    return 0;
                })));
        assertEquals(1, calls.get());
        assertEquals(2, scalar("SELECT stock FROM products WHERE id=1"));
    }

    @Test @DisplayName("B15 — Deadlock 40P01 thật sau first locks riêng; retry whole TX")
    void b15_deadlockThenRetry() throws Exception { runPair(false, false); }

    @Test @DisplayName("B15 — Thứ tự lock 1,2 nhất quán không có vòng chờ")
    void b15_consistentLockOrder() throws Exception { runPair(false, true); }

    @Test @DisplayName("B15 — Serializable write skew 40001 thật; fresh retry bảo vệ invariant")
    void b15_serializationThenRetry() throws Exception { runPair(true, false); }

    private void runPair(boolean serializable, boolean ordered) throws Exception {
        control(); // Marked valid control before any gate: skeleton reports TODO, never timeout.
        var gate = new CyclicBarrier(2);
        var firstCommitted = new CountDownLatch(1);
        var pool = Executors.newFixedThreadPool(2);
        var futures = new ArrayList<Future<Integer>>();
        var attempts = List.of(new AtomicInteger(), new AtomicInteger());
        var states = new ConcurrentLinkedQueue<String>();
        var observed = new ConcurrentLinkedQueue<Long>();
        try {
            for (int worker = 0; worker < 2; worker++) {
                final int index = worker;
                futures.add(pool.submit(() -> {
                    int result = Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 3, c -> {
                    int attempt = attempts.get(index).incrementAndGet();
                    if (serializable && attempt > 1) {
                        try {
                            if (!firstCommitted.await(5, TimeUnit.SECONDS))
                                throw new SQLException("Survivor commit deadline", "57014");
                        } catch (InterruptedException failure) {
                            Thread.currentThread().interrupt();
                            throw new SQLException("Retry gate interrupted", "HY008", failure);
                        }
                    }
                    System.out.println("B15 worker=" + index + " attempt=" + attempt);
                    try {
                        c.setTransactionIsolation(serializable ? Connection.TRANSACTION_SERIALIZABLE
                                : Connection.TRANSACTION_READ_COMMITTED);
                        execute(c, "SET LOCAL lock_timeout='5s'");
                        if (serializable) {
                            long total = scalar(c, "SELECT sum(stock) FROM products WHERE id IN (1,2)");
                            observed.add(total);
                            if (attempt == 1) await(gate);
                            if (attempt == 1 && index == 1) {
                                try {
                                    if (!firstCommitted.await(5, TimeUnit.SECONDS))
                                        throw new SQLException("First writer commit deadline", "57014");
                                } catch (InterruptedException failure) {
                                    Thread.currentThread().interrupt();
                                    throw new SQLException("Writer gate interrupted", "HY008", failure);
                                }
                            }
                            if (total > 1) execute(c, "UPDATE products SET stock=0 WHERE id=" + (index + 1));
                        } else if (ordered) {
                            if (attempt == 1) await(gate); // Before contested first lock.
                            execute(c, "UPDATE products SET stock=stock+1 WHERE id=1");
                            execute(c, "UPDATE products SET stock=stock+1 WHERE id=2");
                        } else {
                            execute(c, "UPDATE products SET stock=stock+1 WHERE id=" + (index + 1));
                            if (attempt == 1) await(gate); // Both distinct first locks acquired.
                            execute(c, "UPDATE products SET stock=stock+1 WHERE id=" + (2 - index));
                        }
                        return attempt;
                    } catch (SQLException failure) {
                        states.add(failure.getSQLState());
                        System.out.println("B15 worker=" + index + " SQLSTATE=" + failure.getSQLState());
                        throw failure;
                    }
                    });
                    firstCommitted.countDown(); // retryTransaction returned only after commit.
                    return result;
                }));
            }
            int totalAttempts = 0;
            for (var f : futures) totalAttempts += f.get(20, TimeUnit.SECONDS);
            assertEquals(ordered ? 2 : 3, totalAttempts);
            assertEquals(ordered ? 0 : 1, states.size());
            if (!ordered) assertEquals(serializable ? "40001" : "40P01", states.element());
            if (serializable) {
                assertEquals(2, observed.stream().filter(n -> n == 2L).count());
                assertTrue(observed.contains(1L)); // New transaction reevaluates business predicate.
                assertEquals(1, scalar("SELECT sum(stock) FROM products"));
            } else {
                assertEquals(3, scalar("SELECT stock FROM products WHERE id=1"));
                assertEquals(3, scalar("SELECT stock FROM products WHERE id=2"));
            }
        } finally {
            futures.forEach(f -> f.cancel(true));
            pool.shutdownNow();
            assertTrue(pool.awaitTermination(12, TimeUnit.SECONDS));
        }
    }

    private void control() throws SQLException {
        int value = Ex01_DeadlockRetry.retryTransaction(fixture.dataSource(), 1, c -> 7);
        assertEquals(7, value);
    }
    private static void await(CyclicBarrier gate) throws SQLException {
        try { gate.await(5, TimeUnit.SECONDS); }
        catch (InterruptedException failure) {
            Thread.currentThread().interrupt(); throw new SQLException("Gate interrupted", "HY008", failure);
        } catch (BrokenBarrierException | TimeoutException failure) {
            throw new SQLException("Gate deadline", "57014", failure);
        }
    }
    private static void execute(Connection c, String sql) throws SQLException {
        try (var s = c.createStatement()) { s.setQueryTimeout(10); s.execute(sql); }
    }
    private long scalar(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection()) { return scalar(c, sql); }
    }
    private static long scalar(Connection c, String sql) throws SQLException {
        try (var s = c.createStatement()) {
            s.setQueryTimeout(10);
            try (var r = s.executeQuery(sql)) { assertTrue(r.next()); return r.getLong(1); }
        }
    }
}
