package phase04.d17_capstone;

import java.io.PrintWriter;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.lang.reflect.Proxy;
import java.math.BigDecimal;
import java.nio.file.Files;
import java.nio.file.Path;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.TreeMap;
import java.util.Map;
import java.util.HashSet;
import java.util.List;
import java.util.NoSuchElementException;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.logging.Logger;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.Timeout;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.d17_capstone.Ex01_OrderPersistence.InsufficientStockException;
import phase04.d17_capstone.Ex01_OrderPersistence.Line;
import phase04.support.PostgresFixture;
import static org.junit.jupiter.api.Assertions.*;

@Execution(ExecutionMode.SAME_THREAD)
@Timeout(60)
class Ex01_OrderPersistenceTest {
    static PostgresFixture fixture;
    DataSource ds;
    @BeforeAll static void start() { fixture = PostgresFixture.start(); }
    @AfterAll static void close() { if (fixture != null) fixture.close(); }
    // Provided frozen schema for non-DDL capstone; no learner migration or transaction answer.
    static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    static final String SEED = """
            INSERT INTO customers(name) VALUES ('owner'),('other'),('empty');
            INSERT INTO products(name,price,stock) VALUES ('A',12.30,10),('B',4.25,1),('limit',0.01,1000);
            """;
    @BeforeEach void reset() throws SQLException { fixture.reset(SCHEMA, SEED); ds = fixture.dataSource(); }

    @Test @DisplayName("B17 — Giá server snapshot, ID sinh mới và input không bị sửa")
    void b17_successServerSnapshotsGeneratedIdsAndImmutableInput() throws Exception {
        execute("INSERT INTO orders(customer_id,status,created_at) VALUES (2,'NEW','2026-01-01T00:00:00Z')");
        List<Line> input = List.of(new Line(2, 1), new Line(1, 2));
        long id = Ex01_OrderPersistence.createOrder(ds, 1, input);
        assertTrue(id > 1); // seed uses identity, no explicit-id sequence collision
        assertEquals(List.of(new Line(2, 1), new Line(1, 2)), input);
        assertEquals(8, stock(1)); assertEquals(0, stock(2));
        assertEquals(2, scalar("SELECT count(*) FROM order_items WHERE order_id=" + id));
        assertEquals("12.30", text("SELECT unit_price FROM order_items WHERE product_id=1"));
        execute("UPDATE products SET price=99.99 WHERE id=1");
        var page = Ex01_OrderPersistence.ordersForCustomer(ds, 1, 0, 100);
        assertEquals(1, page.size());
        var order = page.getFirst();
        assertEquals(id, order.orderId()); assertEquals("NEW", order.status());
        assertNotNull(order.createdAt()); assertEquals(2, order.itemCount());
        assertEquals(new BigDecimal("28.85"), order.total()); // 12.30*2 + 4.25
        assertEquals(0, scalar("SELECT count(*) FROM orders WHERE id=" + id + " AND created_at > CURRENT_TIMESTAMP"));
    }

    @Test @DisplayName("B17 — Tổng NUMERIC lớn không overflow; đơn không item có tổng 0.00")
    void b17_projectionPreservesLargeNumericTotalsAndEmptyOrder() throws Exception {
        execute("UPDATE products SET price=99999999999999999.99 WHERE id=3");
        long id = Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(3, 1000)));
        var row = Ex01_OrderPersistence.ordersForCustomer(ds, 1, 0, 1).getFirst();
        assertEquals(id, row.orderId()); assertEquals(1, row.itemCount());
        assertEquals(new BigDecimal("99999999999999999990.00"), row.total());
        execute("INSERT INTO orders(customer_id,status,created_at) VALUES (3,'CANCELLED','2026-01-01T00:00:00Z')");
        var empty = Ex01_OrderPersistence.ordersForCustomer(ds, 3, 0, 1).getFirst();
        assertEquals("CANCELLED", empty.status()); assertEquals(0, empty.itemCount());
        assertEquals(new BigDecimal("0.00"), empty.total());
    }

    @Test @DisplayName("B17 — Reject product trùng; item đầu thành công, item sau thiếu stock rollback cả đơn")
    void b17_rejectsDuplicateAndRollsBackInsufficientStock() throws Exception {
        long control = Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(1, 1)));
        assertTrue(control > 0); assertEquals(9, stock(1)); // learner success, never inside broad assertThrows
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.createOrder(ds, 1,
                List.of(new Line(1, 1), new Line(1, 1))));
        assertThrows(InsufficientStockException.class, () -> Ex01_OrderPersistence.createOrder(ds, 1,
                List.of(new Line(1, 1), new Line(2, 2)))); // first success, second insufficient
        assertEquals(9, stock(1)); assertEquals(1, stock(2));
        assertEquals(0, scalar("SELECT count(*) FROM orders WHERE customer_id=1"));
        assertEquals(1, scalar("SELECT count(*) FROM order_items"));
    }

    @Test @DisplayName("B17 — Validate null/rỗng/ID/quantity/trùng trước connection và ghi dữ liệu")
    void b17_allInputBoundariesRejectedBeforeConnectionOrWrites() throws Exception {
        assertTrue(Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(3, 1000))) > 0);
        assertEquals(0, stock(3));
        JdbcProbe probe = new JdbcProbe(ds);
        for (List<Line> bad : Arrays.asList(null, List.<Line>of(), Arrays.asList((Line) null),
                List.of(new Line(0, 1)), List.of(new Line(-1, 1)), List.of(new Line(1, -1)),
                List.of(new Line(1, 0)), List.of(new Line(1, 1001)), List.of(new Line(1, 1), new Line(1, 1)))) {
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.createOrder(probe, 1, bad));
        }
        for (long badId : new long[]{0, -1})
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.createOrder(probe, badId, List.of(new Line(1, 1))));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.createOrder(null, 1, List.of(new Line(1, 1))));
        assertEquals(0, probe.connections.get());
        assertEquals(10, stock(1)); assertEquals(1, stock(2));
        assertEquals(1, scalar("SELECT count(*) FROM orders"));
    }

    @Test @DisplayName("Q2 — Customer/product thiếu và SQLException giữa chừng rollback order/items/stock")
    void q02_missingOwnerProductAndSqlFailureRollbackWholeOrder() throws Exception {
        assertTrue(Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(1, 1))) > 0);
        assertThrows(NoSuchElementException.class, () -> Ex01_OrderPersistence.createOrder(ds, 999,
                List.of(new Line(1, 1))));
        assertThrows(NoSuchElementException.class, () -> Ex01_OrderPersistence.createOrder(ds, 1,
                List.of(new Line(1, 1), new Line(999, 1))));
        assertEquals(9, stock(1)); assertEquals(0, scalar("SELECT count(*) FROM orders WHERE customer_id=1"));
        // Provided fault scaffold, not alternative learner implementation: real DB rejects second insert.
        execute("CREATE FUNCTION reject_second_item() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.product_id=2 THEN RAISE EXCEPTION 'forced second item failure' USING ERRCODE='23514'; END IF; RETURN NEW; END $$;"
                + "CREATE TRIGGER reject_second_item BEFORE INSERT ON order_items FOR EACH ROW EXECUTE FUNCTION reject_second_item()");
        SQLException failure = assertThrows(SQLException.class, () -> Ex01_OrderPersistence.createOrder(ds, 1,
                List.of(new Line(1, 1), new Line(2, 1))));
        assertEquals("23514", failure.getSQLState());
        assertEquals(9, stock(1)); assertEquals(1, stock(2));
        assertEquals(1, scalar("SELECT count(*) FROM orders"));
        assertEquals(1, scalar("SELECT count(*) FROM order_items"));
    }

    @Test @DisplayName("Q2 — RuntimeException/Error giữ primary, lỗi rollback suppressed, DB nguyên vẹn")
    void q02_runtimeAndErrorPreservePrimarySuppressRollbackFailure() throws Exception {
        assertTrue(Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(1, 1))) > 0);
        for (Throwable fault : List.of(new IllegalStateException("runtime probe"), new AssertionError("error probe"))) {
            JdbcProbe probe = new JdbcProbe(ds);
            probe.fault = fault; probe.failRollback = true;
            Throwable seen = assertThrows(fault.getClass(), () -> Ex01_OrderPersistence.createOrder(probe, 1,
                    List.of(new Line(1, 1), new Line(2, 1))));
            assertSame(fault, seen);
            assertEquals(1, seen.getSuppressed().length);
            assertInstanceOf(SQLException.class, seen.getSuppressed()[0]);
            assertEquals(9, stock(1)); assertEquals(1, stock(2));
            assertEquals(1, scalar("SELECT count(*) FROM orders"));
            assertEquals(1, scalar("SELECT count(*) FROM order_items"));
        }
    }

    @Test @DisplayName("Q3 — Hai request/backend độc lập không oversell, lượng bán cộng tồn bằng ban đầu")
    void q03_twoIndependentRequestsConserveStock() throws Exception {
        assertTrue(Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(1, 1))) > 0);
        execute("UPDATE products SET stock=1 WHERE id=1");
        JdbcProbe probe = new JdbcProbe(ds);
        probe.ready = new CountDownLatch(2); probe.go = new CountDownLatch(1);
        var pool = Executors.newFixedThreadPool(2);
        boolean terminated;
        try {
            var first = pool.submit(() -> buyLast(probe));
            var second = pool.submit(() -> buyLast(probe));
            assertTrue(probe.ready.await(10, TimeUnit.SECONDS));
            probe.go.countDown();
            int accepted = first.get(25, TimeUnit.SECONDS) + second.get(25, TimeUnit.SECONDS);
            assertEquals(1, accepted); assertEquals(2, new HashSet<>(probe.backendPids).size());
            assertEquals(1, accepted + stock(1));
            assertEquals(1, scalar("SELECT sum(i.quantity) FROM order_items i JOIN orders o ON o.id=i.order_id WHERE o.customer_id=1"));
            assertEquals(1, scalar("SELECT count(*) FROM orders WHERE customer_id=1"));
            System.out.println("B17 independentBackends=2 initialStock=1 accepted=1 finalStock=0");
        } finally {
            probe.go.countDown(); pool.shutdownNow();
            try { terminated = pool.awaitTermination(10, TimeUnit.SECONDS); }
            catch (InterruptedException interrupted) { Thread.currentThread().interrupt(); terminated = false; }
        }
        assertTrue(terminated); // reached only when no primary failure needs preserving
    }

    int buyLast(DataSource source) throws SQLException {
        try { Ex01_OrderPersistence.createOrder(source, 1, List.of(new Line(1, 1))); return 1; }
        catch (InsufficientStockException expected) { return 0; }
    }

    @Test @DisplayName("Q4 — Customer scope, timestamp tie/page bounds và một SQL cho mỗi trang")
    void q04_customerPredicateStableTimestampTiesPageBoundsAndQueryCount() throws Exception {
        long first = Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(1, 1)));
        long foreign = Ex01_OrderPersistence.createOrder(ds, 2, List.of(new Line(1, 1)));
        long second = Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(1, 2)));
        long third = Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(1, 1)));
        execute("UPDATE orders SET created_at='2026-01-01T00:00:00Z'");
        JdbcProbe probe = new JdbcProbe(ds);
        var all = Ex01_OrderPersistence.ordersForCustomer(probe, 1, 0, 100);
        assertEquals(List.of(first, second, third), all.stream().map(Ex01_OrderPersistence.OrderHistory::orderId).toList());
        assertEquals(1, probe.executions.get());
        assertEquals(Instant.parse("2026-01-01T00:00:00Z"), all.getFirst().createdAt());
        assertEquals(new BigDecimal("24.60"), all.get(1).total());
        assertEquals(1, all.get(1).itemCount());
        probe.executions.set(0);
        assertEquals(List.of(first), Ex01_OrderPersistence.ordersForCustomer(probe, 1, 0, 1).stream().map(Ex01_OrderPersistence.OrderHistory::orderId).toList());
        assertEquals(1, probe.executions.get()); // complexity independent of page row count
        assertEquals(second, Ex01_OrderPersistence.ordersForCustomer(ds, 1, 1, 1).getFirst().orderId());
        assertEquals(third, Ex01_OrderPersistence.ordersForCustomer(ds, 1, 2, 1).getFirst().orderId());
        assertTrue(Ex01_OrderPersistence.ordersForCustomer(ds, 1, 3, 1).isEmpty());
        assertTrue(Ex01_OrderPersistence.ordersForCustomer(ds, 1, Integer.MAX_VALUE, 100).isEmpty());
        assertEquals(List.of(foreign), Ex01_OrderPersistence.ordersForCustomer(ds, 2, 0, 100).stream().map(Ex01_OrderPersistence.OrderHistory::orderId).toList());
        assertTrue(Ex01_OrderPersistence.ordersForCustomer(ds, 3, 0, 100).isEmpty());
        assertTrue(Ex01_OrderPersistence.ordersForCustomer(ds, 999, 0, 100).isEmpty());
        int acquired = probe.connections.get();
        for (int[] bad : new int[][]{{-1, 1}, {0, 0}, {0, 101}})
            assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.ordersForCustomer(probe, 1, bad[0], bad[1]));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.ordersForCustomer(probe, 0, 0, 1));
        assertThrows(IllegalArgumentException.class, () -> Ex01_OrderPersistence.ordersForCustomer(null, 1, 0, 1));
        assertEquals(acquired, probe.connections.get());
    }

    @Test @DisplayName("Q4 — Counter bắt N+1 dùng Statement, không chỉ PreparedStatement")
    void q04_counterRejectsDeliberateStatementNPlusOne() throws Exception {
        for (int i = 0; i < 3; i++)
            assertTrue(Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(1, 1))) > 0);
        JdbcProbe probe = new JdbcProbe(ds);
        assertEquals(3, deliberatelyNPlusOneHistory(probe).size());
        assertThrows(AssertionError.class, () -> assertEquals(1, probe.executions.get()));
        assertEquals(4, probe.executions.get()); // one prepared page plus three real Statement queries
    }

    // Deliberate counter regression only: not an alternative learner history projection/answer.
    List<Long> deliberatelyNPlusOneHistory(DataSource source) throws SQLException {
        try (var c = source.getConnection(); var page = c.prepareStatement(
                "SELECT id FROM orders WHERE customer_id=? ORDER BY id LIMIT 3")) {
            page.setQueryTimeout(10); page.setLong(1, 1);
            var ids = new ArrayList<Long>();
            try (var rows = page.executeQuery()) { while (rows.next()) ids.add(rows.getLong(1)); }
            for (long id : ids) {
                try (var item = c.createStatement()) {
                    item.setQueryTimeout(10);
                    try (var rows = item.executeQuery("SELECT count(*) FROM order_items WHERE order_id=" + id)) {
                        assertTrue(rows.next()); assertEquals(1, rows.getLong(1));
                    }
                }
            }
            return ids;
        }
    }

    @Test @DisplayName("Q5 — Lưu SQL/bindings/query count và EXPLAIN thực tế trước/sau index scaffold")
    void q05_historyPlanEvidence_experimentRuns() throws Exception {
        assertTrue(Ex01_OrderPersistence.createOrder(ds, 1, List.of(new Line(1, 1))) > 0);
        // Evidence-only dataset/index scaffold. History SQL itself comes from actual learner execution.
        execute("INSERT INTO orders(customer_id,status,created_at) SELECT 1+g%2,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00'+g*INTERVAL '1 second' FROM generate_series(1,2000) g;"
                + "INSERT INTO order_items(order_id,product_id,quantity,unit_price) SELECT id,1,1,12.30 FROM orders WHERE id>1; ANALYZE");
        JdbcProbe probe = new JdbcProbe(ds);
        assertEquals(20, Ex01_OrderPersistence.ordersForCustomer(probe, 1, 0, 20).size());
        assertEquals(1, probe.executions.get());
        String sql = probe.sql.getFirst();
        var capturedBindings = probe.bindingCalls.getFirst();
        String before = explain(sql, capturedBindings);
        // Provided experiment-only index, not d04's composite-index learner answer.
        execute("CREATE INDEX provided_plan_history ON orders(customer_id); ANALYZE orders");
        String after = explain(sql, capturedBindings);
        assertTrue(before.contains("Buffers:") && before.contains("actual time="));
        assertTrue(after.contains("Buffers:") && after.contains("actual time="));
        Path directory = Path.of("target", "task6-evidence"); Files.createDirectories(directory);
        String evidence = "PostgreSQL=" + text("SHOW server_version") + "\nJDK=" + Runtime.version()
                + "\nDataset: 3 customers, 3 products, 2001 orders/items; customer1=1001 orders, customer2=1000."
                + "\nHistory execute count=1 for 20 rows; SQL=" + sql + "\nBindings=" + probe.bindings.getFirst()
                + "\nBEFORE\n" + before + "\nAFTER provided_plan_history(customer_id)\n" + after
                + "\nLimits: warm cache, tiny disposable dataset, no timing/node golden; index adds write/storage cost."
                + "\nTX: ordered product locks and conditional stock update; atomic DB-only commit, no remote side effects.\n";
        Files.writeString(directory.resolve("history-plan.txt"), evidence);
        System.out.println("B17 historyRows=20 actualQueryCount=1 evidence=target/task6-evidence/history-plan.txt");
    }

    String explain(String sql, List<JdbcProbe.Binding> capturedBindings) throws SQLException {
        try (var c = ds.getConnection(); var s = c.prepareStatement("EXPLAIN (ANALYZE, BUFFERS, FORMAT TEXT) " + sql)) {
            s.setQueryTimeout(10);
            for (var binding : capturedBindings) binding.replay(s);
            try (var rows = s.executeQuery()) {
                StringBuilder plan = new StringBuilder();
                while (rows.next()) plan.append(rows.getString(1)).append('\n');
                return plan.toString();
            }
        }
    }
    long stock(long id) throws SQLException { return scalar("SELECT stock FROM products WHERE id=" + id); }
    long scalar(String sql) throws SQLException { return Long.parseLong(text(sql)); }
    String text(String sql) throws SQLException {
        try (var c = ds.getConnection(); var s = c.createStatement()) {
            s.setQueryTimeout(10);
            try (var rows = s.executeQuery(sql)) { assertTrue(rows.next()); return rows.getString(1); }
        }
    }
    void execute(String sql) throws SQLException {
        try (var c = ds.getConnection(); var s = c.createStatement()) { s.setQueryTimeout(10); s.execute(sql); }
    }

    /** Real JDBC delegate: counts executions, gates connection acquisition, injects post-write failures only. */
    static class JdbcProbe implements DataSource {
        final DataSource delegate;
        final AtomicInteger connections = new AtomicInteger(), executions = new AtomicInteger(), inserts = new AtomicInteger();
        final List<String> sql = Collections.synchronizedList(new ArrayList<>());
        final List<Map<Integer, Object>> bindings = Collections.synchronizedList(new ArrayList<>());
        final List<List<Binding>> bindingCalls = Collections.synchronizedList(new ArrayList<>());
        record Binding(Method method, Object[] arguments) {
            void replay(PreparedStatement statement) throws SQLException {
                try { method.invoke(statement, arguments); }
                catch (InvocationTargetException failure) {
                    if (failure.getCause() instanceof SQLException sql) throw sql;
                    throw new SQLException("Captured binding failed", failure.getCause());
                } catch (ReflectiveOperationException failure) { throw new SQLException("Cannot replay captured binding", failure); }
            }
        }
        final List<Integer> backendPids = Collections.synchronizedList(new ArrayList<>());
        CountDownLatch ready, go;
        Throwable fault;
        boolean failRollback;
        JdbcProbe(DataSource delegate) { this.delegate = delegate; }
        @Override public Connection getConnection() throws SQLException { return wrap(delegate.getConnection()); }
        @Override public Connection getConnection(String user, String password) throws SQLException { return wrap(delegate.getConnection(user, password)); }
        Connection wrap(Connection connection) throws SQLException {
            connections.incrementAndGet();
            try {
                if (ready != null) {
                    try (var s = connection.createStatement()) {
                        s.setQueryTimeout(10);
                        try (var r = s.executeQuery("SELECT pg_backend_pid()")) { r.next(); backendPids.add(r.getInt(1)); }
                    }
                    ready.countDown();
                    if (!go.await(10, TimeUnit.SECONDS)) throw new SQLException("Connection gate timed out");
                }
            } catch (InterruptedException interrupted) {
                Thread.currentThread().interrupt(); connection.close(); throw new SQLException("Connection gate interrupted", interrupted);
            } catch (SQLException failure) { connection.close(); throw failure; }
            return (Connection) Proxy.newProxyInstance(Connection.class.getClassLoader(), new Class<?>[]{Connection.class}, (proxy, method, args) -> {
                Object value;
                try { value = method.invoke(connection, args); }
                catch (InvocationTargetException failure) { throw failure.getCause(); }
                if (method.getName().equals("rollback") && failRollback) throw new SQLException("rollback probe after real rollback");
                if (value instanceof Statement statement) {
                    String preparedSql = args != null && args.length > 0 && args[0] instanceof String query ? query : null;
                    Class<?> type = statement instanceof CallableStatement ? CallableStatement.class
                            : statement instanceof PreparedStatement ? PreparedStatement.class : Statement.class;
                    var params = new TreeMap<Integer, Object>();
                    var calls = new ArrayList<Binding>();
                    return Proxy.newProxyInstance(type.getClassLoader(), new Class<?>[]{type}, (p, m, a) -> {
                        if (m.getName().equals("clearParameters")) { params.clear(); calls.clear(); }
                        if (m.getName().startsWith("set") && a != null && a.length >= 2 && a[0] instanceof Integer index) {
                            params.put(index, a[1]); calls.add(new Binding(m, a.clone()));
                        }
                        if (m.getName().startsWith("execute")) {
                            String query = a != null && a.length > 0 && a[0] instanceof String text ? text : preparedSql;
                            executions.incrementAndGet(); sql.add(query); bindings.add(new TreeMap<>(params));
                            bindingCalls.add(List.copyOf(calls));
                            if (fault != null && query != null && query.startsWith("INSERT INTO order_items")
                                    && inserts.incrementAndGet() == 2) throw fault;
                        }
                        try { return m.invoke(statement, a); }
                        catch (InvocationTargetException failure) { throw failure.getCause(); }
                    });
                }
                return value;
            });
        }
        @Override public PrintWriter getLogWriter() throws SQLException { return delegate.getLogWriter(); }
        @Override public void setLogWriter(PrintWriter writer) throws SQLException { delegate.setLogWriter(writer); }
        @Override public int getLoginTimeout() throws SQLException { return delegate.getLoginTimeout(); }
        @Override public void setLoginTimeout(int seconds) throws SQLException { delegate.setLoginTimeout(seconds); }
        @Override public Logger getParentLogger() { return Logger.getLogger("task6-jdbc-probe"); }
        @Override public <T> T unwrap(Class<T> type) throws SQLException { return delegate.unwrap(type); }
        @Override public boolean isWrapperFor(Class<?> type) throws SQLException { return delegate.isWrapperFor(type); }
    }
}
