package phase04.d09_jdbc;

import static org.junit.jupiter.api.Assertions.*;

import com.zaxxer.hikari.HikariConfig;
import com.zaxxer.hikari.HikariDataSource;
import java.io.ByteArrayOutputStream;
import java.io.PrintStream;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_JdbcResourcesTest {
    private static PostgresFixture fixture;
    // Provided non-DDL schema; independent of learner migrations and JDBC answer SQL.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai');
            INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4),(2,'x'' OR ''1''=''1',5.00,2),(3,'Bulk',0.01,1000);
            INSERT INTO orders(id,customer_id,status,created_at) VALUES (901,1,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00');
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q1 — Order ID số tách khỏi tên product có dạng SQL")
    void q01_bindsNumericOrderAndLiteralProductName() throws SQLException {
        var ds = fixture.dataSource();
        var order = Ex01_JdbcResources.findOrder(ds, 901).orElseThrow();
        assertEquals(new Ex01_JdbcResources.OrderRow(901, 1, Instant.parse("2026-01-01T00:00:00Z"), "NEW"), order);
        assertTrue(Ex01_JdbcResources.findOrder(ds, 999).isEmpty());
        assertEquals(List.of(new Ex01_JdbcResources.Product(1, "Tea", 4, new BigDecimal("12.50"))),
                Ex01_JdbcResources.findProductByName(ds, "Tea"));
        assertEquals(List.of(new Ex01_JdbcResources.Product(2, "x' OR '1'='1", 2, new BigDecimal("5.00"))),
                Ex01_JdbcResources.findProductByName(ds, "x' OR '1'='1"));
        assertTrue(Ex01_JdbcResources.findProductByName(ds, "absent' OR true --").isEmpty());
    }

    @Test @DisplayName("B9 — Conditional stock update, quantity hợp lệ và invalid control")
    void b09_reducesOnlyAvailableStock() throws SQLException {
        var ds = fixture.dataSource();
        assertEquals(1, Ex01_JdbcResources.reduceStock(ds, 1, 2));
        assertEquals(2, stock(1));
        assertEquals(0, Ex01_JdbcResources.reduceStock(ds, 1, 3));
        assertEquals(0, Ex01_JdbcResources.reduceStock(ds, 999, 1));
        for (int quantity : new int[] {0, -1, 1001}) {
            assertThrows(IllegalArgumentException.class, () -> Ex01_JdbcResources.reduceStock(ds, 1, quantity));
            assertEquals(2, stock(1));
        }
        assertEquals(1, Ex01_JdbcResources.reduceStock(ds, 3, 1000));
        assertEquals(0, stock(3));
    }

    @Test @DisplayName("Q4 — Đóng ResultSet, statement rồi connection thật, kể cả khi SQL lỗi")
    void q04_closesRealResourcesOnSuccessAndFailure() throws SQLException {
        List<String> closed = new ArrayList<>();
        DataSource ds = (DataSource) track(fixture.dataSource(), DataSource.class, closed);
        assertTrue(Ex01_JdbcResources.findOrder(ds, 901).isPresent());
        assertEquals(List.of("ResultSet", "PreparedStatement", "Connection"), closed);
        closed.clear();
        assertEquals(1, Ex01_JdbcResources.findProductByName(ds, "Tea").size());
        assertEquals(List.of("ResultSet", "PreparedStatement", "Connection"), closed);
        closed.clear();
        assertEquals(1, Ex01_JdbcResources.reduceStock(ds, 1, 1));
        assertEquals(List.of("PreparedStatement", "Connection"), closed);
        closed.clear();
        execute("ALTER TABLE orders RENAME TO unavailable_orders");
        var failure = assertThrows(SQLException.class, () -> Ex01_JdbcResources.findOrder(ds, 901));
        assertEquals("42P01", failure.getSQLState());
        assertEquals(List.of("PreparedStatement", "Connection"), closed);
    }

    @Test @DisplayName("B9 — Bind literal, SQL failure được trả về; Hikari lease tái sử dụng trong 2 giây")
    void b09_bindsValuesAndReturnsPoolLease() {
        assertTimeoutPreemptively(Duration.ofSeconds(15), () -> {
            HikariConfig config = new HikariConfig();
            config.setJdbcUrl(fixture.jdbcUrl());
            config.setUsername(fixture.username());
            config.setPassword(fixture.password());
            config.setMaximumPoolSize(1);
            config.setMinimumIdle(1);
            config.setConnectionTimeout(2000);
            try (var pool = new HikariDataSource(config)) {
                ByteArrayOutputStream output = new ByteArrayOutputStream();
                PrintStream original = System.out;
                try (var captured = new PrintStream(output)) {
                    System.setOut(captured);
                    assertTrue(Ex01_JdbcResources.findOrder(pool, 901).isPresent());
                    assertEquals(List.of(new Ex01_JdbcResources.Product(2, "x' OR '1'='1", 2, new BigDecimal("5.00"))),
                            Ex01_JdbcResources.findProductByName(pool, "x' OR '1'='1"));
                    assertEquals(1, Ex01_JdbcResources.reduceStock(pool, 1, 1));
                    assertEquals(0, pool.getHikariPoolMXBean().getActiveConnections());
                    execute("ALTER TABLE products RENAME TO unavailable_products");
                    var readFailure = assertThrows(SQLException.class,
                            () -> Ex01_JdbcResources.findProductByName(pool, "Tea"));
                    assertEquals("42P01", readFailure.getSQLState());
                    assertEquals(0, pool.getHikariPoolMXBean().getActiveConnections());
                    var writeFailure = assertThrows(SQLException.class,
                            () -> Ex01_JdbcResources.reduceStock(pool, 1, 1));
                    assertEquals("42P01", writeFailure.getSQLState());
                    assertEquals(0, pool.getHikariPoolMXBean().getActiveConnections());
                    assertTimeoutPreemptively(Duration.ofSeconds(2), () -> {
                        Connection first = pool.getConnection();
                        assertEquals(1, pool.getHikariPoolMXBean().getActiveConnections());
                        first.close();
                        assertTrue(first.isClosed());
                        try (var second = pool.getConnection(); var s = second.createStatement();
                             var r = s.executeQuery("SELECT 1")) {
                            assertTrue(second.getAutoCommit());
                            assertTrue(r.next());
                            assertEquals(1, r.getInt(1));
                        }
                    });
                    assertEquals(0, pool.getHikariPoolMXBean().getActiveConnections());
                } finally { System.setOut(original); }
                assertEquals("", output.toString()); // DAO must not print URL, password or results.
            }
        });
    }

    // Instrument real JDBC calls only; no simulated SQL or canned results.
    private static Object track(Object real, Class<?> type, List<String> closed) {
        return Proxy.newProxyInstance(type.getClassLoader(), new Class<?>[] {type}, (proxy, method, args) -> {
            try {
                Object result = method.invoke(real, args);
                if (method.getName().equals("close")) closed.add(type.getSimpleName());
                if (result instanceof Connection) return track(result, Connection.class, closed);
                if (result instanceof PreparedStatement) return track(result, PreparedStatement.class, closed);
                if (result instanceof ResultSet) return track(result, ResultSet.class, closed);
                return result;
            } catch (InvocationTargetException failure) { throw failure.getCause(); }
        });
    }

    private int stock(long id) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT stock FROM products WHERE id=" + id)) {
            assertTrue(r.next());
            return r.getInt(1);
        }
    }

    private void execute(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute(sql); }
    }
}
