package phase04.d10_jdbc_transactions;

import static org.junit.jupiter.api.Assertions.*;

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.math.BigDecimal;
import java.sql.BatchUpdateException;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.sql.DataSource;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.parallel.Execution;
import org.junit.jupiter.api.parallel.ExecutionMode;
import phase04.support.PostgresFixture;

@Execution(ExecutionMode.SAME_THREAD)
class Ex01_JdbcBatchTest {
    private static PostgresFixture fixture;
    // Provided fixed schema, independent of learner migrations and batch implementation.
    private static final String SCHEMA = """
            CREATE TABLE customers(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE);
            CREATE TABLE products(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,name TEXT NOT NULL UNIQUE,price NUMERIC(19,2) NOT NULL CHECK(price>=0),stock INTEGER NOT NULL CHECK(stock>=0));
            CREATE TABLE orders(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,customer_id BIGINT NOT NULL REFERENCES customers(id),status TEXT NOT NULL CHECK(status IN ('NEW','CANCELLED')),created_at TIMESTAMPTZ NOT NULL);
            CREATE TABLE order_items(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,order_id BIGINT NOT NULL REFERENCES orders(id) ON DELETE CASCADE,product_id BIGINT NOT NULL REFERENCES products(id),quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 1000),unit_price NUMERIC(19,2) NOT NULL CHECK(unit_price>=0),UNIQUE(order_id,product_id));
            """;
    private static final String SEED = """
            INSERT INTO customers(id,name) VALUES (1,'Mai');
            INSERT INTO products(id,name,price,stock) VALUES (1,'Tea',12.50,4),(2,'Book',5.00,4),(3,'Bulk',0.01,1000);
            INSERT INTO orders(id,customer_id,status,created_at) VALUES (900,1,'NEW',TIMESTAMPTZ '2026-01-01 00:00:00+00'),(901,1,'NEW',TIMESTAMPTZ '2026-01-02 00:00:00+00');
            """;

    @BeforeAll static void startDatabase() { fixture = PostgresFixture.start(); }
    @AfterAll static void stopDatabase() { if (fixture != null) fixture.close(); }
    @BeforeEach void resetDatabase() throws SQLException { fixture.reset(SCHEMA, SEED); }

    @Test @DisplayName("Q4 — Batch counts ứng với từng item; giá USD lấy từ DB")
    void q04_checksCountsAndServerPriceSnapshots() throws SQLException {
        createControl();
        assertArrayEquals(new int[] {1, 1}, Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(3, 1000))));
        assertEquals(2, count(901));
        assertEquals(1000, scalar("SELECT quantity FROM order_items WHERE order_id=901 AND product_id=3"));
        execute("UPDATE products SET price=99.00 WHERE id=1");
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement();
             var r = s.executeQuery("SELECT product_id,quantity,unit_price FROM order_items WHERE order_id=900 ORDER BY product_id")) {
            assertTrue(r.next());
            assertEquals(1, r.getLong(1));
            assertEquals(2, r.getInt(2));
            assertEquals(new BigDecimal("12.50"), r.getBigDecimal(3));
            assertTrue(r.next());
            assertEquals(2, r.getLong(1));
            assertEquals(1, r.getInt(2));
            assertEquals(new BigDecimal("5.00"), r.getBigDecimal(3));
            assertFalse(r.next());
        }
    }

    @Test @DisplayName("B10 — Valid-first, quantity 0 second: SQLSTATE và rollback cả batch")
    void b10_batchFailureRollsBack() throws SQLException {
        createControl();
        var failure = assertThrows(BatchUpdateException.class,
                () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                        List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(2, 0))));
        assertEquals("23514", failure.getSQLState());
        assertNotNull(failure.getNextException());
        assertEquals("23514", failure.getNextException().getSQLState());
        assertTrue(failure.getUpdateCounts().length > 0);
        assertUnchanged();
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement(); var r = s.executeQuery("SELECT 1")) {
            assertTrue(c.getAutoCommit());
            assertTrue(r.next());
            assertEquals(1, r.getInt(1));
        }
        assertArrayEquals(new int[] {1}, Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                List.of(new Ex01_JdbcBatch.Line(1, 1))));
        assertEquals(1, count(901));
    }

    @Test @DisplayName("Q2 — Lỗi rollback bị suppressed; BatchUpdateException gốc không bị thay")
    void q02_suppressesRollbackFailureAndKeepsSqlCause() throws SQLException {
        createControl();
        SQLException rollbackFailure = new SQLException("rollback observation failure", "08006");
        DataSource ds = (DataSource) Proxy.newProxyInstance(DataSource.class.getClassLoader(), new Class<?>[] {DataSource.class},
                (proxy, method, args) -> {
                    try {
                        Object result = method.invoke(fixture.dataSource(), args);
                        if (!(result instanceof Connection real)) return result;
                        return Proxy.newProxyInstance(Connection.class.getClassLoader(), new Class<?>[] {Connection.class},
                                (p, m, a) -> {
                                    try {
                                        Object value = m.invoke(real, a);
                                        // Real rollback first; inject only cleanup-report failure, not DB behavior.
                                        if (m.getName().equals("rollback")) throw rollbackFailure;
                                        return value;
                                    } catch (InvocationTargetException failure) { throw failure.getCause(); }
                                });
                    } catch (InvocationTargetException failure) { throw failure.getCause(); }
                });
        var failure = assertThrows(BatchUpdateException.class,
                () -> Ex01_JdbcBatch.insertItems(ds, 901,
                        List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(2, 0))));
        assertEquals("23514", failure.getSQLState());
        assertNotNull(failure.getCause());
        assertArrayEquals(new Throwable[] {rollbackFailure}, failure.getSuppressed());
        assertUnchanged();
    }

    @Test @DisplayName("B10 — Quantity -1/1001, trùng product và FK lỗi không giữ item đầu")
    void b10_rejectsInvalidMembersAtomically() throws SQLException {
        createControl();
        for (int quantity : new int[] {-1, 1001}) {
            var failure = assertThrows(SQLException.class,
                    () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                            List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(2, quantity))));
            assertEquals("23514", failure.getSQLState());
            assertUnchanged();
        }
        var duplicate = assertThrows(SQLException.class,
                () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                        List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(1, 2))));
        assertEquals("23505", duplicate.getSQLState());
        assertUnchanged();
        var missingOrder = assertThrows(SQLException.class,
                () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 999,
                        List.of(new Ex01_JdbcBatch.Line(1, 1))));
        assertEquals("23503", missingOrder.getSQLState());
        assertUnchanged();
        var missingProduct = assertThrows(SQLException.class,
                () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901,
                        List.of(new Ex01_JdbcBatch.Line(1, 1), new Ex01_JdbcBatch.Line(999, 1))));
        assertEquals("02000", missingProduct.getSQLState());
        assertUnchanged();
    }

    @Test @DisplayName("B10 — Batch null/rỗng không thành công giả")
    void b10_rejectsEmptyBatch() throws SQLException {
        createControl();
        assertThrows(IllegalArgumentException.class, () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901, null));
        assertThrows(IllegalArgumentException.class, () -> Ex01_JdbcBatch.insertItems(fixture.dataSource(), 901, List.of()));
        assertUnchanged();
    }

    private void createControl() throws SQLException {
        assertArrayEquals(new int[] {1, 1}, Ex01_JdbcBatch.insertItems(fixture.dataSource(), 900,
                List.of(new Ex01_JdbcBatch.Line(1, 2), new Ex01_JdbcBatch.Line(2, 1))));
        assertEquals(2, count(900));
    }

    private void assertUnchanged() throws SQLException {
        assertEquals(2, count(900));
        assertEquals(0, count(901));
        assertEquals(2, scalar("SELECT count(*) FROM order_items"));
        assertEquals(4, scalar("SELECT stock FROM products WHERE id=1"));
    }

    private long count(long orderId) throws SQLException {
        return scalar("SELECT count(*) FROM order_items WHERE order_id=" + orderId);
    }

    private long scalar(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement(); var r = s.executeQuery(sql)) {
            assertTrue(r.next());
            return r.getLong(1);
        }
    }

    private void execute(String sql) throws SQLException {
        try (var c = fixture.dataSource().getConnection(); var s = c.createStatement()) { s.execute(sql); }
    }
}
